# Curriculum Vitae

# Education

|Degree| Field | Institution|Date|
|  :---  |  :---  |  :---  | :---  |
|Ph.D.| Technology-Integrated Assessment | University of Victoria| 2026|
|    M.Ed. | Distance Education   | Athabasca University| 2014 |
|  B.Ed.     | Physical Education | University of Lethbridge      |2001|
|  B.A.     | Physical Education      | Trinity Western University    | 1997  |
: {.striped}


<!--
\* I completed candidacy in 2022 and have since published 2 of 3 papers for my dissertation. The third paper is in process and I expect to be complete by the summer of 2025.

\*\*Thesis: *Structured Student Interactions in Online Distance Education: Exploring the Study Buddy Activity* <http://hdl.handle.net/10791/47>
-->



# Certifications

-   British Columbia Ministry of Education Teacher Regulation Branch
    -   Professional Certificate #L178396
-   Alberta Education
    -   Permanent Professional Certificate #254651U

# Employment History

|Dates| Position, Employer       |
|  ---  |  ---  |
|2024 - |  Director, Technology-integrated Learning and Assessment, Trinity Western University     |
|2016 - 2024|  Manager of Online Learning and Instructional Technologies, Trinity Western University     |
| 2019 - | Sessional Instructor, Trinity Western University | 
| 2019 - 2022 | Sessional Instructor, University of Victoria | 
|  2016     | Coordinator for Educational Technologies, Thompson Rivers University (Sessional )      |
| 2015 - 2017 | Open Education Research Fellow |
|  2010 - 2016     | E-Learning Facilitator, Thompson Rivers University      |
|  2009 - 2013     | Research Assistant, Athabasca University      |
|  2007 - 2010     | High School Teacher and Athletic Director, St. Ann's Academy      |
|  2005 - 2007     | English Teacher, Ogaki and Nagoya, Japan      |
: {.striped tbl-colwidths="[20,80]"}

# Refereed Journal Articles


-   **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024a). Developing the Technology-Integrated Assessment Framework. *The Open/Technology in Education, Society, and Scholarship Association Journal, 4*(1), 1–19. <https://doi.org/10.18357/otessaj.2024.4.1.63>
-   **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024b). Technology-Integrated Assessment: A Literature Review. *The Open/Technology in Education, Society, and Scholarship Association Journal, 4*(1), 1–48. <https://doi.org/10.18357/otessaj.2024.4.1.57>
-   **Madland, C.**, & Richards, G. (2016). Enhancing Student-Student Online Interaction: Exploring the Study Buddy Peer Review Activity. *International Review of Research in Open and Distance Learning, 17*(3). <https://doi.org/10.19173/irrodl.v17i3.2179>

<!-- ## Forthcoming -->

<!-- - Cui, H., Irvine, V., Miller, M., & **Madland, C.** (In Preparation). Creating Capacity for Digital Transformation of Education: Mode and Disciplinary Barriers in the Development of Highly Qualified Personnel. *Canadian Journal of Learning and Technology*. -->
<!-- - Irvine, V., Paskevicius, M., **Madland, C.**, McCue, R., & Roberts, V. (In Preparation). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. *Open Praxis*.  -->

# Refereed Proceedings

-   **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024, June). Evolving our understanding of technology-integrated assessment: A review of the literature and development of a new framework. *Open/Technology in Education, Society, and Scholarship Association at Congress of the Social Sciences and Humanities*, Montreal, QC, CA. <https://doi.org/10.18357/otessac.2024.4.1.393>
-   Cui, H., Irvine, V., Miller, M., & **Madland, C.** (2024). Creating Capacity for Digital Transformation of Education: Mode and Disciplinary Barriers in the Development of Highly Qualified Personnel. *Proceedings of the Open/Technology in Education, Society, and Scholarship Association Conference. Open/Technology in Education, Society, and Scholarship Association Conference,* Montréal, QC.
-   Irvine, V., Paskevicius, M., **Madland, C.**, McCue, R., & Roberts, V. (2022). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. *The Open/Technology in Education, Society, and Scholarship Association Conference, 2*(1), 1–9. <https://doi.org/10.18357/otessac.2022.2.1.419>
-   **Madland, C.**, Ofosuhene, M., & Adkins, J. (2022). Digital Platforms and Algorithmic Erasure: What are the Implications? *Open/Technology in Education, Society, and Scholarship Association at Congress of the Social Sciences and Humanities*, Online. <https://doi.org/10.18357/otessac.2022.2.1.137>
-   Irvine, V., Paskevicius, M., **Madland, C**., McCue, R., & Roberts, V. (2022). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. Proceedings of the Open/Technology in Education, Society, and Scholarship Association Conference, 1–3. <https://doi.org/10.18357/otessac.2022.2.1.419>
-   **Madland, C.**, & Restoule, J.-P. (2021). Self-Determination in Indigenous Online Education. *The Open/Technology in Education, Society, and Scholarship Association Conference, 1* (1), 1–7. <https://doi.org/10.18357/otessac.2021.1.1.147>

# Refereed Presentations

- **Madland, C.**, & Mitchell. (2025, June 5). Assessment for Equity: Openness and DEI in your Grading Architecture [50-min Workshop]. *Open/Technology in Education, Society, and Scholarship Association Conference, Victoria, BC.* <https://cmadland.github.io/slides/posts/otessa25-grading/#/title-slide>
- **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2025, June 6). Technology-integrated Assessment Scale [20-min Presentation]. *Open/Technology in Education, Society, and Scholarship Association Conference, Victoria, BC.*  <https://cmadland.github.io/slides/posts/otessa25-scale/#/title-slide>
- **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024, June). Evolving our understanding of technology-integrated assessment: A review of the literature and development of a new framework. *Open/Technology in Education, Society, and Scholarship Association*, Montreal, QC, CA. <https://cmadland.github.io/blog/posts/deck-otessa24/#/title-slide>
-   **Madland, C.** (2023, June). Research? Which Research? Technology, Assessment, and Higher Education in Tension. *Open/Technology in Education, Society, and Scholarship Association*, Online. 
-   **Madland, C.** (2022, May). Assessment and Digital Technology in Higher Education: A Review of the Literature. *Open/Technology in Education, Society, and Scholarship Association*, Online. <https://cmadland.github.io/decks/otessa22---assessment-and-digital-technology-in-higher-education.html#otessa22---assessment-and-digital-technology-in-higher-education>
-   Irvine, V., Paskevicius, M., **Madland, C.**, McCue, R., Roberts, V. (2022, May). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. OTESSA 2022, Online. <https://otessa.github.io/2022/wedesday-may-18-2022.html#parallel-session-11.1-transitions-of-online-learning-and-teaching-pse-open>
-   Marjanovic, K., Golland, B., **Madland, C.** (2022, May). Share Access! Using Bookdown to Remove Barriers and Open Up Learning. OTESSA 2022, Online. <https://otessa.github.io/2022/friday-may-20-2022.html#share-access-using-bookdown-to-remove-barriers-and-open-up-learning>
-   **Madland, C.**, Ofosuhene, M., and Adkins, J., (2022, May). Digital platforms and algorithmic erasure: What are the implications? OTESSA 2022, Online. <https://otessa.github.io/2022/tuesday-may-17-2022.html#digital-platforms-and-algorithmic-erasure-what-are-the-implications-practice-oriented>
-   **Madland, C.** (2021, September). Assessment Approaches in Higher Education. Let’s Talk about Teaching, Victoria, BC.
-   Clark Gray, B., & **Madland, C.** (2021, June). Resisting Surveillance Technology. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/resisting-surveillance-technology/>
-   **Madland, C.**, & James, H. (2021, June). Experiencing a cognitive apprenticeship in the context of co-designing and co-teaching an undergraduate course. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/experiencing-a-cognitive-apprenticeship-in-the-context-of-co-designing-and-co-teaching-an-undergraduate-course/>
-   **Madland, C.** (2021, May). Humanizing Assessment in Online Higher Education. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/humanizing-assessment-in-online-higher-education/>
-   **Madland, C.** (2021, May). Indigenous Digital Self-Determination. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/indigenous-digital-self-determination/>
-   Chan, K., Irvine, V., & **Madland, C.** (2020, July). Decentralized Synchronous Learning Pods For Learner Discourse and Community-Building: An Alternative to Breakout Rooms. *Let’s Talk about Teaching, Victoria, BC.*
-   Irvine, V., James, H., **Madland, C.**, & McCue, R. (2020, July). Teaching in the Open: Supporting Open Access Designs for Social Justice. *Let’s Talk about Teaching, Victoria, BC.*
-   James, H., & **Madland, C.** (2020, July). Co-Designing and Co-Teaching an Online Course. *Let’s Talk about Teaching, Victoria, BC.*
-   **Madland, C.**, & Irvine, V. (2020, April 17). Self-Determination in Indigenous Online Education \[Roundtable Session\]. AERA Annual Meeting, San Francisco, CA. (Conference Canceled). <http://tinyurl.com/vp8h3q8>
-   **Madland, C.** (2019, June). Indigenous and Open Education: A contradiction? CSSHE Conference, Vancouver, BC.
-   **Madland, C.** (2017). Flexible Infrastructure to Support the Design and Delivery of Online Learning. ICDE World Conference for Online Learning, Toronto.
-   **Madland, C.** (2016, November). The Open Advantage. Open Education, Richmond, VA.
-   Hendricks, C., Jhangiani, R., & **Madland, C.** (2016, March). Experiences, perceptions, and outcomes of BC students using open textbooks: Research from the BC OER Research Fellows. BCcampus Festival of Learning.
-   **Madland, C.** (2016a, February). Building Trust and Community with Initiative Tasks. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2016, February). Communities of Inquiry to Ignite Learning. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2016, April). Enhancing Learning through OER and Open Platforms. OER16, Edinburgh, Scotland.
-   **Madland, C.** (2016, April). Exploring the Remix Hypothesis. Open Education Global Conference, Krakow, Poland.
-   **Madland, C.** (2015, November). Open and Connected Faculty Development. Open Education, Vancouver, BC.
-   **Madland, C.** (2014, February). Structured Student Interactions. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2014, May). Encouraging Deeper Approaches to Learning. Open Learning Faculty Members Workshop, Kamloops, BC.
-   **Madland, C.** (2014, May). Structured Student Interactions. CNIE Conference, Kamloops, BC.
-   **Madland, C.** (2013, September). Structuring Student Interactions in Online Distance Learning: Exploring the Study Buddy Activity. Athabasca University Graduate Students’ Conference, Edmonton, AB.
-   **Madland, C.** (2012, February). Engaging Students with Video. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2012, May). Online Faculty Development. Southern Alberta Institute of Technology Faculty Showcase, Calgary, AB.


# Non-Refereed Presentations

-   **Madland, C.** (2012, May). Outside the Box Feedback with Adobe Acrobat. Open Learning Faculty Members Workshop, Kamloops, BC.
-   **Madland, C.** (2011, October). Thinking Despite the Box: Designing Interaction in Blackboard. Teaching with Technology Series, Kamloops, BC.
-   **Madland, C.** (2010, October). Twitter in Higher Education. Teaching with Technology Series, Kamloops, BC.

# Media

- Krinsky, S., & Bosley, R. (October 8, 2024). Alt Grading in Physical Education, Canadian Grading Reforms, and Technology-Integrated Assessment: An Interview with Colin Madland (No. 65) [Podcast]. <https://thegradingpod.com/episodes/65-alt-grading-in-physical-education-canadian-grading-reforms-and-technology-integrated-assessment-an-interview-with-colin-madland/>
- Greene, T. (2020). Valerie Irvine and Colin Madland [Broadcast]. [Podcast]. <https://www.spreaker.com/episode/valerie-irvine-and-colin-madland--23026170>

# Research Dissemination

-  "Technology-Integrated Assessment in Higher Education"; Kigali, Rwanda; Uganda; and Pan-Africa Christian University, Nairobi, Kenya, November 2024
- "Self-Paced Learning in Higher Education", Pan-Africa Christian University, Nairobi, Kenya, May 2023
- "What is Assessment", TWU Faculty Professional Learning.  March 2023 <https://cmadland.github.io/decks/twu-faculty-professional-learning.html>.

# Research Funding

- BCcampus Research Fellowship, 2022 ($6000)
- University of Victoria Graduate Student Award, September 2019 ($5000)
- University of Victoria Graduate Student Award, September 2018 ($5000)
- TRU Open Learning Presentation Fund, April 2016 ($5000)
- Open Education Resources Research Fellow, Open Education Group, 2015-16 (5000 USD)
- Athabasca University Tim Byrne Memorial Scholarship (for academic excellence along with an outstanding thesis or project), nominated by the Centre for Distance Education, June 2014. ($1000)
- Athabasca University Student Travel Award, September 2013. ($800)
- Athabasca University Graduate Student Mission Critical Research Fund, April 2013. ($420)
- Athabasca University Access to Research Tools, April 2013. ($300)

# Teaching Activities

Undergraduate and **Graduate**

|Year| Course       | Title      | Credit Hours/Units      | Students  |
|  :---:  |  ---  |  :---:  |   :---:  | :---: |
|  Summer 2019     |  EDCI 335     |   Learning Design    |  1.5     |  37   |
|  Summer 2019     |  EDCI 339     |   Open and Distributed Learning    |  1.5     |  39    |
|  Summer 2019     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  3    |
|  Summer 2020     |  EDCI 335     |   Learning Design    |  1.5     |  56    |
|  Summer 2020     |  EDCI 339     |   Open and Distributed Learning     |  1.5     |  59    |
|  Summer 2020     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  16    |
|  Fall 2020     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  10    |
|  Spring 2021     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  7    |
|  Summer 2021     |  EDCI 335     |   Learning Design    |  1.5     |  40    |
|  Fall 2021     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  7 (All in Nigeria)    |
|  Fall 2021     |  EDCI 335     |   Learning Design    |  1.5     |  41    |
|  Spring 2022    |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  11    |
|  Summer 2022     |  EDCI 338     |   Social Media and Personalized Learning    |  1.5     |  39    |
|  Spring 2023   |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  1 (DS)    |
|  Fall 2023   |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  6 (4 in Nigeria)    |
|  Fall 2023   |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  4    |
|  Fall 2024     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  1    |
|  Fall 2024     |  LDRS 463     |   Transformational Blended Learning    |  3     |  2    |
|  Summer 2025     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  1    |
|  Summer 2025     |  LDRS 463     |   Transformational Blended Learning    |  3     |  4    |
: {.striped}

# Curriculum Development Projects

-   LDRS 101 - Learning in a Digital World
-   LDRS 663 - Transformational Blended Learning
-   EDCI 335 - Learning Design
-   EDCI 339 - Distributed and Open Learning
-   Teaching Online Effectively (TOnE)
-   Online Teaching and Learning
-   Online Facilitation Skills for Student Learning, Engagement, and Retention
-   Course Management Strategies
-   Online Student Success

# Service

## Reviewer

-   Open/Technology in Education, Society, and Scholarship Association (OTESSA) Conference
-   Open/Technology in Education Society, and Scholarship Association (OTESSA) Journal,
-   International Review of Research in Open and Distributed Learning (IRRODL),
-   Research in Learning Technology (ISSOTL)
-   Teaching & Learning Inquiry
-   International Journal of E-Learning and Distance Education
  
## Committees
-   Founding Board Member, [Open/Technology in Education, Society, and Scholarship Association (OTESSA)](https://otessa.org), 2019-present
-   Faculty Professional Learning Committee, Trinity Western University, 2016-present
-   Board of Directors, Canadian Network for Innovation in Education (CNIE), 2016-2018
-   Chair, Thompson Rivers University Graduate Studies Committee of Senate, November 2015-April 2016
-   Thompson Rivers University Graduate Studies Committee of Senate, November 2012 - November 2015
-   Academic Planning and Priorities Committee of Senate, October 2015-April 2016

# Awards

-   Outstanding Service Award from Thompson Rivers University Open Learning, September 2012.

# Professional Learning

-   Coaching for Leaders, Smart + Savvy and Associates (2018)
-   [Interculturalizing the Curriculum](https://www.tru.ca/intercultural/inventory.html), Thompson Rivers University (2015)


```{=html}
<!--
## St. Ann's Academy (High School), Kamloops, BC
2007 - 2010

- Physical Education
- Digital Media and Design
  
## Heritage Christian Academy (High School), Calgary, AB

2002 - 2005

- Physical Education
- Sports Medicine
- Outdoor Education
- Digital Media and Design

## WR Myers High School, Taber, AB

2002 (Temporary Contract)

- Physical Education
- Outdoor Education
- English

## Assistant Language Teacher, Nagoya and Ogaki, Japan

2005 - 2007

- Assisted Japanese Teachers of English with lessons and lesson planning
- Engaged in cultural exchange activities
-->
```

<!--
# EXPERIENCE

## Sessional Instructor, Trinity Western University

2019-Present

-   LDRS 663 - Coaching for Transformational Blended Learning (2019, 2020, 2021, 2023, 2024 - Graduate course)

## Sessional Instructor, University of Victoria

2019-2022

-   EDCI 335 - Learning Design (2019, 2020, 2021)
-   EDCI 339 - Open and Distributed Learning (2019 and 2020)
-   EDCI 338 - Social Media and Personalized Learning (2022)


# RELATED EXPERIENCE

## Research Assistant, Athabasca University, Athabasca, AB

December 2010-December 2013 and November 2009-January 2010

-   performed literature searches using electronic databases
-   collated and reported results of literature searches
-   provided advice about and edited survey items
-   composed, sent and tracked emails sent to students inviting them to participate in a SSHRC-funded research study

## High School Teacher & Athletic Director, St. Ann’s Academy, Kamloops, BC

September 2007-March 2010

-   recruited and trained up to 50 volunteer coaches, managers and student and parent volunteers per year
-   designed, planned and taught digital media courses for high school students
-   introduced revised assessment practices in high school physical education classes
-   planned and hosted 8 tournaments per year in various sports

## English Teacher, Ogaki and Nagoya, Japan

October 2005-July 2007

-   assisted Japanese Teachers of English with course development, lesson planning and team-teaching in the classroom
-   taught academic English to Japanese students wishing to study in North American universities

## Challenge Course Facilitator, Trinity Western University, Langley, BC

1998-1999 (Seasonal)

-   conducted needs assessment interviews for corporate and community clients
-   planned safe and effective team-building tasks using low and high ropes course activities
-   facilitated discussions among participants designed to draw out lessons learned about communication, teamwork, leadership and other collaborative skills
-   evaluated the effectiveness of challenge course experiences
-->