---
bibliography: references.bib
---

# Philosophy of Teaching and Learning

In my research and practice of teaching and learning in higher education, I ground my work in several broad principles related to ontological (who we are), teleological (what we do), and epistemological (how we know) perspectives.

## Who We Are

Ontological perspectives are primary and can be summarized in the statement:

> All people have inherent value and have the right to dignified and respectful interactions with others.

This principle is expanded in the 5Rs of Indigenous education [@tessaro2018]: respect, responsibility, relevance, reciprocity, and relationships. The 5Rs serve as a set of values grounded in the inherent value of all people and the importance of intentional work to foreground the perspectives of equity-deserving groups, and the ultimate goal of education is to empower learners to fully realize their value and to flourish in who they are.

## What We Do

Teleological perspectives flow from who we are.

> Learning is idealized as a cognitive apprenticeship.

We know from @bloom1984 that the most profound learning experiences occur in the context of sustained discourse between the learner and the instructor (who can sometimes be a peer or other interested observer). This sense-making process must include the learner actively exercising evaluative judgement [@tai2018] through the comparison of their own work to the work of both novice and expert others.

## How We Know

Epistemological perspectives flow from who we are and what we do.

> If there is an end, it is when the teacher has become unnecessary.

Coming to know something (learning) is a result of what we do. When learners strive for a cognitive goal, they iterate based on their past knowledge combined with feedback they receive regarding their performance in relation to the goal [@carless2019; @hattie2007]. Consequently, learning is inextricably tied to the process of assessing learning. When a learner is able to generate their own feedback on performance, they no longer need the instructor and can sustain their own learning [@boud2016].

# References