project:
  type: website
  output-dir: docs

website:
  title: "Colin Madland"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Home
#      - cv.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - cv.qmd
      - philosophy.qmd
      - timeline.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
  pdf: default
  docx: 
    reference-doc: reference.docx
bibliography: references.bib
csl: apa.csl


