project:
  type: website
  output-dir: docs

website:
  title: "Colin Madland"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - about.qmd
          - index.qmd
      - section: "Layout"
        contents:
          - about.qmd
          - index.qmd
          - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
  pdf: default



