project:
  type: website
  output-dir: docs

website:
  title: "Colin Madland"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Home
#      - cv.qmd
  sidebar: false
    # style: "docked"
    # search: true
    # contents:
    #   - timeline.qmd
    #   # - cv.qmd
    #   # - philosophy.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    execute:
      echo: false
      warning: false



  # pdf: default
  docx:
    execute: 
      echo: false
    reference-doc: reference.docx
    bibliography: references.bib
    csl: apa.csl


