project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
    - cv.qmd
    - philosophy.qmd
    - teaching-dossier.qmd
    - research.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    execute:
      echo: false
      warning: false



  # pdf: default
  # docx:
  #   execute: 
  #     echo: false
  #   reference-doc: reference.docx
  #   bibliography: references.bib
  #   csl: apa.csl


