# Curriculum Vitae

# Education

|Degree| Field | Institution|Date|
|  :---:  |  :---:  |  :---:  | :---:  |
|Ph.D.| Technology-Integrated Assessment | University of Victoria|Expected 2025\*|
|    M.Ed. | Distance Education   |Athabasca University|2014\*\*|
|  B.Ed.     | Physical Education | University of Lethbridge      |2001|
|  B.A.     | Physical Education      | Trinity Western University    | 1997  |
: {.striped}


\* I completed candidacy in 2022 and have since published 2 of 3 papers for my dissertation. The third paper is in process and I expect to be complete by the summer of 2025.

\*\*Thesis: *Structured Student Interactions in Online Distance Education: Exploring the Study Buddy Activity* <http://hdl.handle.net/10791/47>



# Certifications

-   British Columbia Ministry of Education Teacher Regulation Branch
    -   Professional Certificate #L178396
-   Alberta Education
    -   Permanent Professional Certificate #254651U

# Employment History

|Dates| Position, Employer       |
|  ---  |  ---  |
|2016 - |  Manager of Online Learning and Instructional Technologies, Trinity Western University     |
| 2019 - | Sessional Instructor, Trinity Western University | 
| 2019 - 2022 | Sessional Instructor, University of Victoria | 
|  2016     | Coordinator for Educational Technologies, Thompson Rivers University (Sessional )      |
| 2015 - 2017 | Open Education Research Fellow |
|  2010 - 2016     | E-Learning Facilitator, Thompson Rivers University      |
|  2009 - 2013     | Research Assistant, Athabasca University      |
|  2007 - 2010     | High School Teacher and Athletic Director, St. Ann's Academy      |
|  2005 - 2007     | English Teacher, Ogaki and Nagoya, Japan      |
: {.striped tbl-colwidths="[20,80]"}

# Refereed Journal Articles


-   **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024a). Developing the Technology-Integrated Assessment Framework. *The Open/Technology in Education, Society, and Scholarship Association Journal, 4*(1), 1–19. <https://doi.org/10.18357/otessaj.2024.4.1.63>
-   **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024b). Technology-Integrated Assessment: A Literature Review. *The Open/Technology in Education, Society, and Scholarship Association Journal, 4*(1), 1–48. <https://doi.org/10.18357/otessaj.2024.4.1.57>
-   **Madland, C.**, & Richards, G. (2016). Enhancing Student-Student Online Interaction: Exploring the Study Buddy Peer Review Activity. *International Review of Research in Open and Distance Learning, 17*(3). <https://doi.org/10.19173/irrodl.v17i3.2179>

## Forthcoming

- Cui, H., Irvine, V., Miller, M., & **Madland, C.** (In Preparation). Creating Capacity for Digital Transformation of Education: Mode and Disciplinary Barriers in the Development of Highly Qualified Personnel. *Canadian Journal of Learning and Technology*.
- Irvine, V., Paskevicius, M., **Madland, C.**, McCue, R., & Roberts, V. (In Preparation). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. *Open Praxis*. 

# Refereed Proceedings

-   **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024, June). Evolving our understanding of technology-integrated assessment: A review of the literature and development of a new framework. *Open/Technology in Education, Society, and Scholarship Association at Congress of the Social Sciences and Humanities*, Montreal, QC, CA. <https://doi.org/10.18357/otessac.2024.4.1.393>
-   **Madland, C.**, Ofosuhene, M., & Adkins, J. (2022). Digital Platforms and Algorithmic Erasure: What are the Implications? *Open/Technology in Education, Society, and Scholarship Association at Congress of the Social Sciences and Humanities*, Online. <https://doi.org/10.18357/otessac.2022.2.1.137>
-   Irvine, V., Paskevicius, M., **Madland, C**., McCue, R., & Roberts, V. (2022). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. Proceedings of the Open/Technology in Education, Society, and Scholarship Association Conference, 1–3. <https://doi.org/10.18357/otessac.2022.2.1.419>
-   **Madland, C.**, & Restoule, J.-P. (2021). Self-Determination in Indigenous Online Education. *The Open/Technology in Education, Society, and Scholarship Association Conference, 1* (1), 1–7. <https://doi.org/10.18357/otessac.2021.1.1.147>

# Refereed Presentations

- **Madland, C.**, Irvine, V., DeLuca, C., & Bulut, O. (2024, June). Evolving our understanding of technology-integrated assessment: A review of the literature and development of a new framework. *Open/Technology in Education, Society, and Scholarship Association*, Montreal, QC, CA. <https://cmadland.github.io/blog/posts/deck-otessa24/#/title-slide>
-   **Madland, C.** (2023, June). Research? Which Research? Technology, Assessment, and Higher Education in Tension. *Open/Technology in Education, Society, and Scholarship Association*, Online. 
-   **Madland, C.** (2022, May). Assessment and Digital Technology in Higher Education: A Review of the Literature. *Open/Technology in Education, Society, and Scholarship Association*, Online. <https://cmadland.github.io/decks/otessa22---assessment-and-digital-technology-in-higher-education.html#otessa22---assessment-and-digital-technology-in-higher-education>
-   Irvine, V., Paskevicius, M., **Madland, C.**, McCue, R., Roberts, V. (2022, May). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. OTESSA 2022, Online. <https://otessa.github.io/2022/wedesday-may-18-2022.html#parallel-session-11.1-transitions-of-online-learning-and-teaching-pse-open>
-   Marjanovic, K., Golland, B., **Madland, C.** (2022, May). Share Access! Using Bookdown to Remove Barriers and Open Up Learning. OTESSA 2022, Online. <https://otessa.github.io/2022/friday-may-20-2022.html#share-access-using-bookdown-to-remove-barriers-and-open-up-learning>
-   **Madland, C.**, Ofosuhene, M., and Adkins, J., (2022, May). Digital platforms and algorithmic erasure: What are the implications? OTESSA 2022, Online. <https://otessa.github.io/2022/tuesday-may-17-2022.html#digital-platforms-and-algorithmic-erasure-what-are-the-implications-practice-oriented>
-   **Madland, C.** (2021, September). Assessment Approaches in Higher Education. Let’s Talk about Teaching, Victoria, BC.
-   Clark Gray, B., & **Madland, C.** (2021, June). Resisting Surveillance Technology. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/resisting-surveillance-technology/>
-   **Madland, C.**, & James, H. (2021, June). Experiencing a cognitive apprenticeship in the context of co-designing and co-teaching an undergraduate course. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/experiencing-a-cognitive-apprenticeship-in-the-context-of-co-designing-and-co-teaching-an-undergraduate-course/>
-   **Madland, C.** (2021, May). Humanizing Assessment in Online Higher Education. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/humanizing-assessment-in-online-higher-education/>
-   **Madland, C.** (2021, May). Indigenous Digital Self-Determination. OTESSA 2021, Online. <https://otessa.org/2021/abstracts/indigenous-digital-self-determination/>
-   Chan, K., Irvine, V., & **Madland, C.** (2020, July). Decentralized Synchronous Learning Pods For Learner Discourse and Community-Building: An Alternative to Breakout Rooms. Let’s Talk about Teaching, Victoria, BC.
-   Irvine, V., James, H., **Madland, C.**, & McCue, R. (2020, July). Teaching in the Open: Supporting Open Access Designs for Social Justice. Let’s Talk about Teaching, Victoria, BC.
-   James, H., & **Madland, C.** (2020, July). Co-Designing and Co-Teaching an Online Course. Let’s Talk about Teaching, Victoria, BC.
-   **Madland, C.**, & Irvine, V. (2020, April 17). Self-Determination in Indigenous Online Education \[Roundtable Session\]. AERA Annual Meeting, San Francisco, CA. (Conference Canceled). <http://tinyurl.com/vp8h3q8>
-   **Madland, C.** (2019, June). Indigenous and Open Education: A contradiction? CSSHE Conference, Vancouver, BC.
-   **Madland, C.** (2017). Flexible Infrastructure to Support the Design and Delivery of Online Learning. ICDE World Conference for Online Learning, Toronto.
-   **Madland, C.** (2016, November). The Open Advantage. Open Education, Richmond, VA.
-   Hendricks, C., Jhangiani, R., & **Madland, C.** (2016, March). Experiences, perceptions, and outcomes of BC students using open textbooks: Research from the BC OER Research Fellows. BCcampus Festival of Learning.
-   **Madland, C.** (2016a, February). Building Trust and Community with Initiative Tasks. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2016, February). Communities of Inquiry to Ignite Learning. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2016, April). Enhancing Learning through OER and Open Platforms. OER16, Edinburgh, Scotland.
-   **Madland, C.** (2016, April). Exploring the Remix Hypothesis. Open Education Global Conference, Krakow, Poland.
-   **Madland, C.** (2015, November). Open and Connected Faculty Development. Open Education, Vancouver, BC.
-   **Madland, C.** (2014, February). Structured Student Interactions. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2014, May). Encouraging Deeper Approaches to Learning. Open Learning Faculty Members Workshop, Kamloops, BC.
-   **Madland, C.** (2014, May). Structured Student Interactions. CNIE Conference, Kamloops, BC.
-   **Madland, C.** (2013, September). Structuring Student Interactions in Online Distance Learning: Exploring the Study Buddy Activity. Athabasca University Graduate Students’ Conference, Edmonton, AB.
-   **Madland, C.** (2012, February). Engaging Students with Video. Teaching Practices Colloquium, Kamloops, BC.
-   **Madland, C.** (2012, May). Online Faculty Development. Southern Alberta Institute of Technology Faculty Showcase, Calgary, AB.


# Non-Refereed Presentations

-   **Madland, C.** (2012, May). Outside the Box Feedback with Adobe Acrobat. Open Learning Faculty Members Workshop, Kamloops, BC.
-   **Madland, C.** (2011, October). Thinking Despite the Box: Designing Interaction in Blackboard. Teaching with Technology Series, Kamloops, BC.
-   **Madland, C.** (2010, October). Twitter in Higher Education. Teaching with Technology Series, Kamloops, BC.

# Media

- Krinsky, S., & Bosley, R. (October 8, 2024). Alt Grading in Physical Education, Canadian Grading Reforms, and Technology-Integrated Assessment: An Interview with Colin Madland (No. 65) [Podcast]. <https://thegradingpod.com/episodes/65-alt-grading-in-physical-education-canadian-grading-reforms-and-technology-integrated-assessment-an-interview-with-colin-madland/>
- Greene, T. (2020). Valerie Irvine and Colin Madland [Broadcast]. [Podcast]. <https://www.spreaker.com/episode/valerie-irvine-and-colin-madland--23026170>

# Research Dissemination

-  [UPCOMING] "Technology-Integrated Assessment in Higher Education"; Kigali, Rwanda; Uganda; and Pan-Africa Christian University, Nairobi, Kenya, November 2024
- "Self-Paced Learning in Higher Education", Pan-Africa Christian University, Nairobi, Kenya, May 2023
- "What is Assessment", TWU Faculty Professional Learning.  March 2023 <https://cmadland.github.io/decks/twu-faculty-professional-learning.html>.

# Research Funding

- BCcampus Research Fellowship, 2022 ($6000)
- University of Victoria Graduate Student Award, September 2019 ($5000)
- University of Victoria Graduate Student Award, September 2018 ($5000)
- TRU Open Learning Presentation Fund, April 2016 ($5000)
- Open Education Resources Research Fellow, Open Education Group, 2015-16 (5000 USD)
- Athabasca University Tim Byrne Memorial Scholarship (for academic excellence along with an outstanding thesis or project), nominated by the Centre for Distance Education, June 2014. ($1000)
- Athabasca University Student Travel Award, September 2013. ($800)
- Athabasca University Graduate Student Mission Critical Research Fund, April 2013. ($420)
- Athabasca University Access to Research Tools, April 2013. ($300)

# Teaching Activities

Undergraduate and **Graduate**

|Year| Course       | Title      | Credit Hours/Units      | Students  |
|  :---:  |  ---  |  :---:  |   :---:  | :---: |
|  Summer 2019     |  EDCI 335     |   Learning Design    |  1.5     |  ~30    |
|  Summer 2019     |  EDCI 339     |   Open and Distributed Learning    |  1.5     |  ~30    |
|  Summer 2019     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  3    |
|  Summer 2020     |  EDCI 335     |   Learning Design    |  1.5     |  ~30    |
|  Summer 2020     |  EDCI 339     |   Open and Distributed Learning     |  1.5     |  ~30    |
|  Summer 2020     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  16    |
|  Fall 2020     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  10    |
|  Spring 2021     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  7    |
|  Summer 2021     |  EDCI 335     |   Learning Design    |  1.5     |  ~30    |
|  Fall 2021     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  7 (All in Nigeria)    |
|  Spring 2022    |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  11    |
|  Summer 2022     |  EDCI 338     |   Social Media and Personalized Learning    |  1.5     |  ~30    |
|  Spring 2023   |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  1 (DS)    |
|  Fall 2023   |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  6 (4 in Nigeria)    |
|  Fall 2023   |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  4    |
|  Fall 2024     |  **LDRS 663**     |   Transformational Blended Learning    |  3     |  1    |
|  Fall 2024     |  LDRS 463     |   Transformational Blended Learning    |  3     |  2    |
: {.striped}

# Curriculum Development Projects

-   LDRS 627 - Adult Learning (Course Revision)
-   LDRS 101 - Learning in a Digital World
-   LDRS 663 - Transformational Blended Learning
-   EDCI 335 - Learning Design
-   EDCI 339 - Distributed and Open Learning
-   Teaching Online Effectively (TOnE)
-   Online Teaching and Learning
-   Online Facilitation Skills for Student Learning, Engagement, and Retention
-   Course Management Strategies
-   Online Student Success

# Service

## Reviewer

-   Open/Technology in Education, Society, and Scholarship Association (OTESSA) Conference
-   Open/Technology in Education Society, and Scholarship Association (OTESSA) Journal,
-   International Review of Research in Open and Distributed Learning (IRRODL),
-   Research in Learning Technology (ISSOTL)
-   Teaching & Learning Inquiry
-   International Journal of E-Learning and Distance Education
  
## Committees
-   Founding Board Member, [Open/Technology in Education, Society, and Scholarship Association (OTESSA)](https://otessa.org), 2019-present
-   Faculty Professional Learning Committee, Trinity Western University, 2016-present
-   Board of Directors, Canadian Network for Innovation in Education (CNIE), two year appointment beginning June 2016.
-   Chair, Thompson Rivers University Graduate Studies Committee of Senate, November 2015-April 2016
-   Thompson Rivers University Graduate Studies Committee of Senate, November 2012 - November 2015
-   Academic Planning and Priorities Committee of Senate, October 2015-April 2016

# Awards

-   Outstanding Service Award from Thompson Rivers University Open Learning, September 2012.

# Professional Learning

-   Coaching for Leaders, Smart + Savvy and Associates (2018)
-   [Interculturalizing the Curriculum](https://www.tru.ca/intercultural/inventory.html), Thompson Rivers University (2015)


# Research Program

Educational assessment is at the heart of robust formal education systems and has been deeply impacted by both COVID-19 and by the broad emergence of generative artificial intelligence (genAI). My research program is focused, in the short-term, on refining and operationalizing our technology integrated assessment framework (TIAF) [@madlandDevelopingTechnologyIntegratedAssessment2024] in the context of emerging technologies, such as genAI and artificial/virtual reality (AR/VR).  In the longer term, especially considering this opportunity with the Werklund School of Education, there is much work to be done to operationalize the refined TIAF by continuing to build a scale to be used to help individual educators, K-12 schools and districts, higher education departments, centres for teaching and learning, scholars of teaching and learning, and/or any other interested stakeholder to explore and understand the impacts of emerging technologies on assessment design and practice, and, by extension, to transform assessment practice in both fornal and informal learning environments. The potential for transformative impact on education systems by paying attention to technology-integrated assessment is significant, as Ramsden claims, "assessment always defines the actual curriculum" [-@ramsdenLearningTeachHigher2003, p. 182]. I believe that transforming technology-integrated assessment practices is one of the most powerful levers we have in the drive to "increase access to impactful and future-focused education" [@AheadTomorrowStrategic].

Given the long history of "emerging educational technologies" that have come and gone (e.g. teaching machines, SecondLife, commercial massively open online courses) without significantly transforming education, it is wise to understand that genAI and AR/VR are likely the most recent addition to this list. A research program that is focused on a single tool or implementation of a tool may have limited sustainability as tools come and go. Consequently, the TIAF is technology agnostic. 

The TIAF comprises four primary constructs (assessment purpose, duty of care, technology acceptance, and measurement), each capable of supporting robust interdisciplinary investigations. Questions that arise from the *assessment purpose* construct include investigating the impacts of AI use on the balance of assessment of/for/as learning in K-12 and higher education practice. More specifically, emerging technologies including genAI and AR/VR, have provided opportunity for instructors to focus more on the *process* of learning and assessment for/as learning compared to the *products* of learning. The *duty of care* construct provides myriad opportunities for investigations into the ethics of genAI or AR/VR use and the ways in which it is important to prioritize human characteristics and relationships in education. Note especially the differential impacts on racialized learners and their challenges with using AI-powered remote proctoring services during the COVID-19 pandemic (see my proceeding that highlights my viral experience with this issue [@madlandDigitalPlatformsAlgorithmic2022]). At the same time, there are notable benefits for equity-deserving groups (e.g. neurodivergent learners) who may be able to leverage boutique, privacy-protecting genAI models to preview and refine their work prior to submission to an instructor. Duty of care is especially important to prioritize in Indigenous learning contexts where there is a long history of exploitation, extraction, and exterimnation in the context of education (see my proceeding exploring this issue [@madlandSelfDeterminationIndigenousOnline2021]). The *technology acceptance* construct leads to questions about managing technological and pedagogical change in contexts with a focus on technology adoption by instructors. Lasting transformation of educational systems requires deep and careful work in managing change. My work as Manager of Online Learning and Instructional Technology has given me clear insight and direct experience in managing and transforming educational systems and technological infrastructure at an enterprise level. This experience provides crucial context for my research into technology acceptance and adoption by the full breadth of stakeholders, from learners, to instructors, support staff, and senior administrators and board-level executives. Lastly, the *assessment design* construct offers many opportunities to consider pedagogical designs and architectures that maximize the impact of quality learning experiences. Too often, universal design for learning (UDL) is an afterthought or an add-on to existing educational and assessment designs, however in this framework, intentional focus is brough to bear on the up-front design of learning environments which are human-centred, equitable, inclusive, and accessible.

The technology-integrated assessment framework as a whole and each individual construct described within present rich opportunities for research on learning through emerging digital technologies. This wide variety of possible approaches to investigating emerging technologies in education leads to multiple opportunities for transdisciplinary, quantitative, qualitative, and mixed research collaborations including educators, ethicists, neuropsychologists, computer scientists, environmental and climate scientists, scholars of leadership, and practicing educational technologists. Further, as the framework is embedded within the 5Rs of Indigenous education, there are multiple possibilities for collaborating with Indigenous scholars and the University of Calgary Office of Indigenous Engagement to explore these and other questions specific to Indigenous communities as we journey together towards reconciliation and renewal [@officeofindigenousengagementIiTaapohtop].

# Teaching and Leadership

Teaching is a profound passion of mine, particularly when it allows me to apply my research findings in the classroom. My teaching experience spans K-25 in both public and private high schools in BC and Alberta; internationally as an assistant language teacher in Japan; and in both undergraduate and graduate courses in higher education. I have taught a diverse range of subjects in K-12, including physical education, digital media studies, outdoor education, sports medicine, science, English, and math. 

At the University of Victoria, I co-designed and taught three online undergraduate courses: Learning Design, Distributed and Open Learning, and Social Media and Personalized Learning. These courses use WordPress as the primary hub of networked interactions, enabling students to personalize their web presence while acquiring critical digital literacy skills by engaging with the open web. (see my 2022 proceedings on multi-section course design [@irvineMultiSectionOpenCourse2022a] as an example of how I share my practice in scholarly venues). 

One of the highlights of my undergraduate teaching experience was co-designing and teaching in parallel with a fellow Ph.D. student during the early stages of the global COVID-19 pandemic. This collaborative process was mutually supportive and helped us navigate the complexities of teaching undergraduates in an innovative, technology-integrated context. Our experience is documented in a presentation at the OTESSA21 conference at the Congress of the Social Sciences and Humanities.
I also co-designed and taught Coaching for Transformational Blended Learning and have been contracted to revise Theory and Practice of Adult Education, courses in the Graduate Certificate in Adult Learning: Coaching and Facilitation at Trinity Western University.  These courses take an experiential approach to coaching individual learners and facilitating group processes in educational contexts. At the undergraduate level at TWU, I collaborated with an instructional designer to create an introductory online course called Learning with Technology which will enrol its first learners in the Fall of 2024. This course helps learners understand the affordances of technology for sense-making in learning environments by teaching them a technology-integrated workflow that maintains their personal privacy and teaches learners how to build networks of knowledge and learning using WordPress.

Since 2010, I have been primarily employed as academic management supporting technology-integrated teaching and learning, including faculty support roles at Thompson Rivers University (2010-2016) and currently at Trinity Western University (2016-present). In my current role, I manage a remote team of 15 people, including instructional designers, digital course producers, media creators, and education coaches and facilitators. We are currently working to design or revise over 100 courses in the TWU Bachelor of Arts in Leadership and Master of Arts in Leadership programs for flexible, community-connected delivery. In 2023, I traveled to Kenya to provide two days of faculty training on creating and managing courses in online modalities. I have supported the technology-integrated learning and reflective practice of teacher candidates in the TWU School of Education by initiating and sustaining the use of WordPress for creating professional portfolios that demonstrate competence in each of the Professional Standards for BC Educators. Additionally, I was invited as a guest speaker to present my research in technology-integrated Indigenous education to a class of teacher candidates in the University of Victoria teacher education program.

# Service 

I have been actively involved in university service both at TRU and TWU. At TRU, I served as a staff representative on the Graduate Studies Committee, including a brief tenure as Chair. At TWU, I have been a member of the Faculty Professional Learning Committee, advising the Associate Vice-Provost of Teaching and Learning on matters related to teaching excellence, education technology, and planning the annual faculty retreat. I played a pivotal role in leading the COVID-19 pivot to emergency remote teaching, supporting faculty in radically transforming their practice on short notice. This experience, despite its challenges, was immensely meaningful. In 2022, with the rise of generative artificial intelligence (ChatGPT) in higher education, I was appointed to the committee that drafted TWU's policy and recommendations for navigating teaching and learning with AI tools.

In 2019, I was invited to join the inaugural board of the Open/Technology in Education, Society, and Scholarship Association (OTESSA), a member association of the Federation for the Humanities and Social Sciences. OTESSA is dedicated to supporting technology-enhanced teaching and learning from K-20+ and exploring the societal impact of openness and technology. Despite the cancellation of our first conference in 2020, I co-chaired the inaugural conference in 2021 and remain actively involved on the board, including being deeply involved with the creation of technological infrastructure and operations to support this rapidly growing scholarly organization.

I have served as a reviewer for multiple academic journals, including the Open/Technology in Education Society and Scholarship Association (OTESSA) Journal, Teaching & Learning Inquiry, Research in Learning Technology, the International Journal of E-Learning and Distance Education, and the International Review of Research in Open and Distributed Learning.


# Contributions and Aspirations

My Ph.D. research focuses on understanding technology-integrated assessment practices, reflecting their growing importance in education today. I am privileged to have distinguished committee members from across Canada: Dr. Valerie Irvine (Supervisor, University of Victoria Director of the Technology Integration and Evaluation Research Lab and President of the Open/Technology in Education, Society, and Scholarship Association), Dr. Christopher DeLuca (Committee Member, Queen’s University Associate Dean of Graduate Studies), and Dr. Okan Bulut (Committee Member, Associate Professor of Measurement, Evaluation and Data Science, University of Alberta and University of Alberta President’s Research Prize Recipient). I spearheaded an investigation into prevalent technology-integrated assessment practices as documented in the literature [@madlandTechnologyIntegratedAssessmentLiterature2024]. Building on these findings and leveraging our expertise in educational technology, measurement, and classroom assessment, we developed the TIAF that emphasizes the 5Rs of Indigenous education (respect, relevance, reciprocity, responsibility, and relationships), and the duty of care instructors owe to learners [@madlandDevelopingTechnologyIntegratedAssessment2024]. The TIAF is the contribution to the fields of educational technology, instructional design, and assessment of which I am most proud and hopeful. In the constant push and pull to integrate the latest emerging technologies, we must not forget that learning is a necessarily human process. 

The final paper of my dissertation, which I expect to complete by the summer of 2025, will center on exploring the quantitative structure of the framework in order to refine and simplify it. Once this refining work has been through this first iteration, I look forward to being able to engage with the questions highlighted in my research proposal section in order to develop a diagnostic instrument based on the TIAF for use by individual educators and larger organizations. This diagnostic tool can then begin to generate data that can be used to highlight challenges in the current model of learning and assessment and then effect change based on our findings. Systemic transformation of educational and assessment systems is a significant challenge and we must "harness the power of research and innovation" [@AheadTomorrowStrategic] in order to progress. In a transformed system, education will become less susceptible to the overstated claims of the educational technology industry and more willing to engage in the thoughtful integration of technologies that enhance uniquely human capabilities.

To this point in my career, I have been completing my PhD part-time while engaged in a full-time career in higher education. This has left me with few options for finding funding (e.g, SSHRC funding is only recently available for part-time students, but I am no longer eligible because I am too far along in my program.) I look forward to being able to apply much more of my effort and energy into securing funding, not only through the Tri-Council agencies, but also through government, university, and other external sources. For example, I am privileged to have extensive backgroung with the Technology Integration and Evaluation (TIE) Lab at the University of Victoria where I have been mentored in strategies for securing funding from agencies like the [Canada Foundation for Innovation](https://www.innovation.ca/) (CFI) which matches seed funding at a rate of 4:1. This would allow me to leverage start-up funds provided in this position and quadruple the financial impact of that initial funding. My supervisor and mentor used this strategy to raise $1.4 million ($780,000 from CFI, the largest amount at UVic) to support the development of the TIE Lab.

My career thus far has balanced experiences in both K-12 and higher education. At the University of Calgary, I would have the opportunity to impact learning and assessment with technology at all levels from K-25 and beyond. The framework developed through my dissertation emphasizes the duty of care owed to learners and the 5Rs of Indigenous education, both of which are critical to human flourishing in the current technology-saturated context of formal education. This work is inherently collaborative, and I look forward to working with colleagues in the Werklund School of Education to advance progressive formal education. 

# Evidence of Collaboration

I have prioritised collaboration throughout my career. All of my published journal articles and proceedings have been the result of rich collaborations across disciplinary areas and often across institutions. I have collaborated with at least 16 different research partners during my career and 7 different teaching partners since 2019. While I have not been in a role that allows me to supervise graduate students, I am regularly asked to provide peer mentorship to new Masters and PhD students as well as new sessional instructors (see my presentation on a collaborative teaching experience in 2021 [@madlandExperiencingCognitiveApprenticeship2021]).

# Contact Information for Three Referees


Dr. Valerie Irvine (Ph.D. Supervisor)  
Director, Technology Integration and Evaluation Research Lab  
University of Victoria  
virvine@uvic.ca   

Dr. Griff Richards (Retired; M.Ed. supervisor)  
Athabasca University   
jgriffr@gmail.com  

Dr. Michele Jacobsen  
Professor, Werklund School of Education  
University of Calgary  
dmjacobs@ucalgary.ca   

{{< pagebreak >}}


## References



```{=html}
<!--
## St. Ann's Academy (High School), Kamloops, BC
2007 - 2010

- Physical Education
- Digital Media and Design
  
## Heritage Christian Academy (High School), Calgary, AB

2002 - 2005

- Physical Education
- Sports Medicine
- Outdoor Education
- Digital Media and Design

## WR Myers High School, Taber, AB

2002 (Temporary Contract)

- Physical Education
- Outdoor Education
- English

## Assistant Language Teacher, Nagoya and Ogaki, Japan

2005 - 2007

- Assisted Japanese Teachers of English with lessons and lesson planning
- Engaged in cultural exchange activities
-->
```

<!--
# EXPERIENCE

## Sessional Instructor, Trinity Western University

2019-Present

-   LDRS 663 - Coaching for Transformational Blended Learning (2019, 2020, 2021, 2023, 2024 - Graduate course)

## Sessional Instructor, University of Victoria

2019-2022

-   EDCI 335 - Learning Design (2019, 2020, 2021)
-   EDCI 339 - Open and Distributed Learning (2019 and 2020)
-   EDCI 338 - Social Media and Personalized Learning (2022)


# RELATED EXPERIENCE

## Research Assistant, Athabasca University, Athabasca, AB

December 2010-December 2013 and November 2009-January 2010

-   performed literature searches using electronic databases
-   collated and reported results of literature searches
-   provided advice about and edited survey items
-   composed, sent and tracked emails sent to students inviting them to participate in a SSHRC-funded research study

## High School Teacher & Athletic Director, St. Ann’s Academy, Kamloops, BC

September 2007-March 2010

-   recruited and trained up to 50 volunteer coaches, managers and student and parent volunteers per year
-   designed, planned and taught digital media courses for high school students
-   introduced revised assessment practices in high school physical education classes
-   planned and hosted 8 tournaments per year in various sports

## English Teacher, Ogaki and Nagoya, Japan

October 2005-July 2007

-   assisted Japanese Teachers of English with course development, lesson planning and team-teaching in the classroom
-   taught academic English to Japanese students wishing to study in North American universities

## Challenge Course Facilitator, Trinity Western University, Langley, BC

1998-1999 (Seasonal)

-   conducted needs assessment interviews for corporate and community clients
-   planned safe and effective team-building tasks using low and high ropes course activities
-   facilitated discussions among participants designed to draw out lessons learned about communication, teamwork, leadership and other collaborative skills
-   evaluated the effectiveness of challenge course experiences
-->