December 30, 2024

Dr. Alexa DeGagne, Chair  
Centre for Interdisciplinary Studies  
Faculty of Humanities and Social Sciences  
Athabasca University

**RE: Application for the Position of Assistant Professor, Open, Digital, and Distance Education**

Dear Dr. DeGagne and Search Committee,

Thank you for taking the time to review my application package for this role. I know it is a time intensive process, having led and been a part of numerous hiring committees. \ Please find enclosed my application to be considered for both academic positions currently posted in the Centre for Interdisciplinary Studies in the Faculty of Social Sciences; namely, the two Assistant Professors of Distance Education positions, as I am eligible for both areas of focus under **Position A** (as it relates to instructional/learning design) and **Position B** (as it relates to blended or online education for rural/remote underserved populations and Indigenous methods in education/distance education).

Having completed master’s coursework at Athabasca University and doctoral coursework at the University of Victoria (in addition to courses from the University of British Columbia and the University of Alberta as part of the Western Dean’s Agreement), I have had an excellent foundation for advancing my research program. Both my academic research and community-based research have centred around learning design, assessment in technology-integrated environments (e.g., blended, online), and inclusive and relational practices to support underserved populations (e.g., Indigenous, remote). 

A key output from my dissertation research was the Technology-integrated Assessment Framework (TIAF) [@madlandDevelopingTechnologyIntegratedAssessment2024]. The framework highlights the importance of integrating Indigenous knowledge systems and methodologies in technology-integrated learning environments during the instructional/learning design phase of course development. The enclosed *Research Effectiveness* document highlights key areas of research that flow from the TIAF, including operationalizing the framework for use as a tool to guide individual instructors or departments in exploring their approaches to technology-integrated assessment in higher education. Also included in this document are links to a recently published article on the TIAF and two other outputs related to my scholarly work in Indigenous learning contexts and a proceeding that resulted from an experience i had with automated computer vision software.

The enclosed *Teaching Dossier* documents the courses I have taught since 2019, when I began my PhD studies, as well as highlights of the learner experience surveys associated with those courses. Missing data indicates that there were insufficient responses to report data. One of the key takeaways for me was the feedabck I received early in my teaching career about my own feedback practices. Since then I have worked diligently to ensure that the structures in my course designs allow and encourage prompt and relational assessment feedback for learners. I have also enclosed as separate uploads, a sample course syllabus and a brief statement outlining my teaching philosophy.


## Contact Information for Three Referees

Dr. Valerie Irvine (Ph.D. Supervisor)  
Director, Technology Integration and Evaluation Research Lab  
University of Victoria  
virvine@uvic.ca

Dr. Griff Richards (Retired; M.Ed. supervisor)  
Athabasca University  
jgriffr@gmail.com

Dr. Micheal Paskevicius 
Associate Professor, Educational Technology  
University of Victoria  
mpaskevi@uvic.ca

Thank you again for taking the time to review my application package. If you have any questions, please do not hesitate to reach out via email (cmadland@uvic.ca) or by phone (1-778-257-3533).

Sincerely,

Colin Madland



## References



<!--
- Co-creating safe spaces for inquiry into meaningful questions and challenges

  - Rs – respect, relevance, reciprocity, responsibility, relationsdhip

  - Inclusion

  - Relevance

  - Duty of care

  - Diversity creates the conditions for new ideas

  - relationship

- Fostering curiosity about the world, why it is the way it is, and what we can do to improve it

  - Relevance

  - Learner autonomy and agency

- Learning can be a difficult process of transformation

  - Learning happens best when learners feel like they have permission to be wrong

  - Learning requires multiple opportunities for practice to build competence

  - Shuell (1986, p. 429), “If students are to learn desired outcomes in a reasonably effective manner, then the teacher’s fundamental task is to get students to engage in learning activities that are likely to result in their achieving those outcomes. It is important to remember that what the student does is more important than what the teacher does.”

  - 

- Assessment strategies and practices are the curriculum

  - Assessment of/for/as learning



-->