---
bibliography: references.bib
---

# Philosophy of Teaching and Learning

In my research and practice of teaching and learning in higher education, I ground my work in three broad principles related to ontological (who we are), teleological (what we do), and epistemological (how we know) perspectives.

## Who We Are

Ontological perspectives are foundational and can be summarized in the statement:

> Those who seek to learn to improve themselves and the world around them have inherent dignity and value.

This principle is expanded in the 5 Rs of Indigenous education [@tessaro2018]: respect, responsibility, relevance, reciprocity, and relationships. The 5 Rs serve as a set of values grounded in the inherent value of all people and the importance of intentional work to foreground the perspectives of equity-deserving groups. When diversity, equity, and inclusion are prioritized and co-created, the entire community of learners benefits from working in an environment where it is safe to be different and/or wrong. The ultimate goal of education is to empower learners to fully realize their purpose and to flourish in their efforts to improve the world around them.

## What We Do

Teleological perspectives are derived from who we are and inform the actions we take to empower learners.

> Learning is idealized as a cognitive apprenticeship which supports the process of sense-making in the context of complex ideas.

We know from @bloom1984 that the most profound learning experiences occur in the context of sustained discourse between a learner (or maybe two or three) and an instructor (who can sometimes be a peer or other interested observer). This sense-making process must include the learner actively drawing connections between ideas and drawing conclusions that are relevant to their own contexts. Sense-making is often a difficult and tentative process, so it is incumbent on the instructor to allow learners to do the work of learning and to recognize that not all learners will achieve at the same pace. Learners exercise autonomy and agency when they are encouraged to exercise evaluative judgement [@tai2018] through the comparison of their own work to the work of both novice and expert others.The task of assessment is a similar process of the instructor making sense of what the learner has demonstrated in their process and the products of their work.



## How We Know

Epistemological perspectives are derived from who we are and what we do.

> If there is an end, it is when the teacher has become unnecessary.

Coming to know something (learning) is a result of what we do. When learners strive for a cognitive goal, they iterate based on their past knowledge combined with feedback they receive regarding their performance in relation to the goal [@carless2019; @hattie2007]. Consequently, learning is inextricably tied to the process of assessing learning. When a learner is able to generate their own feedback on performance, they no longer need the instructor and can sustain their own learning [@boud2016].

- 
- Co-creating safe spaces for inquiry into meaningful questions and challenges
  - 	 Rs – respect, relevance, reciprocity, responsibility, relationsdhip
  - 	Inclusion
  - 	Relevance
  - 	Duty of care
  - 	Diversity creates the conditions for new ideas
  - 	relationship
- Fostering curiosity about the world, why it is the way it is, and what we can do to improve it
  - 	Relevance
  - 	Learner autonomy and agency
- Learning can be a difficult process of transformation
  - 	Learning happens best when learners feel like they have permission to be wrong
  - 	Learning requires multiple opportunities for practice to build competence
  - 	Shuell (1986, p. 429), “If students are to learn desired outcomes in a reasonably effective manner, then the teacher’s fundamental task is to get students to engage in learning activities that are likely to result in their achieving those outcomes. It is important to remember that what the student does is more important than what the teacher does.”
- Assessment strategies and practices are the curriculum
  - 	Assessment of/for/as learning	

# References