# Service 

I have been actively involved in university service both at TRU and TWU. At TRU, I served as a staff representative on the Graduate Studies Committee, including a brief tenure as Chair. At TWU, I have been a member of the Faculty Professional Learning Committee, advising the Associate Vice-Provost of Teaching and Learning on matters related to teaching excellence, education technology, and planning the annual faculty retreat. I played a pivotal role in leading the COVID-19 pivot to emergency remote teaching, supporting faculty in radically transforming their practice on short notice. This experience, despite its challenges, was immensely meaningful. In 2022, with the rise of generative artificial intelligence (ChatGPT) in higher education, I was appointed to the committee that drafted TWU's policy and recommendations for navigating teaching and learning with AI tools.

In 2019, I was invited to join the inaugural board of the Open/Technology in Education, Society, and Scholarship Association (OTESSA), a member association of the Federation for the Humanities and Social Sciences. OTESSA is dedicated to supporting technology-enhanced teaching and learning from K-20+ and exploring the societal impact of openness and technology. Despite the cancellation of our first conference in 2020, I co-chaired the inaugural conference in 2021 and remain actively involved on the board, including being deeply involved with the creation of technological infrastructure and operations to support this rapidly growing scholarly organization.

I have served as a reviewer for multiple academic journals, including the Open/Technology in Education Society and Scholarship Association (OTESSA) Journal, Teaching & Learning Inquiry, Research in Learning Technology, the International Journal of E-Learning and Distance Education, and the International Review of Research in Open and Distributed Learning.


# Contributions and Aspirations

My Ph.D. research focuses on understanding technology-integrated assessment practices, reflecting their growing importance in education today. I am privileged to have distinguished committee members from across Canada: Dr. Valerie Irvine (Supervisor, University of Victoria Director of the Technology Integration and Evaluation Research Lab and President of the Open/Technology in Education, Society, and Scholarship Association), Dr. Christopher DeLuca (Committee Member, Queen’s University Associate Dean of Graduate Studies), and Dr. Okan Bulut (Committee Member, Associate Professor of Measurement, Evaluation and Data Science, University of Alberta and University of Alberta President’s Research Prize Recipient). I spearheaded an investigation into prevalent technology-integrated assessment practices as documented in the literature [@madlandTechnologyIntegratedAssessmentLiterature2024]. Building on these findings and leveraging our expertise in educational technology, measurement, and classroom assessment, we developed the TIAF that emphasizes the 5Rs of Indigenous education (respect, relevance, reciprocity, responsibility, and relationships), and the duty of care instructors owe to learners [@madlandDevelopingTechnologyIntegratedAssessment2024]. The TIAF is the contribution to the fields of educational technology, instructional design, and assessment of which I am most proud and hopeful. In the constant push and pull to integrate the latest emerging technologies, we must not forget that learning is a necessarily human process. 

The final paper of my dissertation, which I expect to complete by the summer of 2025, will center on exploring the quantitative structure of the framework in order to refine and simplify it. Once this refining work has been through this first iteration, I look forward to being able to engage with the questions highlighted in my research proposal section in order to develop a diagnostic instrument based on the TIAF for use by individual educators and larger organizations. This diagnostic tool can then begin to generate data that can be used to highlight challenges in the current model of learning and assessment and then effect change based on our findings. Systemic transformation of educational and assessment systems is a significant challenge and we must "harness the power of research and innovation" [@AheadTomorrowStrategic] in order to progress. In a transformed system, education will become less susceptible to the overstated claims of the educational technology industry and more willing to engage in the thoughtful integration of technologies that enhance uniquely human capabilities.

To this point in my career, I have been completing my PhD part-time while engaged in a full-time career in higher education. This has left me with few options for finding funding (e.g, SSHRC funding is only recently available for part-time students, but I am no longer eligible because I am too far along in my program.) I look forward to being able to apply much more of my effort and energy into securing funding, not only through the Tri-Council agencies, but also through government, university, and other external sources. For example, I am privileged to have extensive backgroung with the Technology Integration and Evaluation (TIE) Lab at the University of Victoria where I have been mentored in strategies for securing funding from agencies like the [Canada Foundation for Innovation](https://www.innovation.ca/) (CFI) which matches seed funding at a rate of 4:1. This would allow me to leverage start-up funds provided in this position and quadruple the financial impact of that initial funding. My supervisor and mentor used this strategy to raise $1.4 million ($780,000 from CFI, the largest amount at UVic) to support the development of the TIE Lab.

My career thus far has balanced experiences in both K-12 and higher education. At the University of Calgary, I would have the opportunity to impact learning and assessment with technology at all levels from K-25 and beyond. The framework developed through my dissertation emphasizes the duty of care owed to learners and the 5Rs of Indigenous education, both of which are critical to human flourishing in the current technology-saturated context of formal education. This work is inherently collaborative, and I look forward to working with colleagues in the Werklund School of Education to advance progressive formal education. 

# Evidence of Collaboration

I have prioritised collaboration throughout my career. All of my published journal articles and proceedings have been the result of rich collaborations across disciplinary areas and often across institutions. I have collaborated with at least 16 different research partners during my career and 7 different teaching partners since 2019. While I have not been in a role that allows me to supervise graduate students, I am regularly asked to provide peer mentorship to new Masters and PhD students as well as new sessional instructors (see my presentation on a collaborative teaching experience in 2021 [@madlandExperiencingCognitiveApprenticeship2021]).