<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.8">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ont-tech-letter</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-79bb3942e891885f9f7af119cd221462.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-154b719f064caf484ddc87df1a7af2f6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Curriculum Vitae</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../philosophy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Philosophy of Teaching and Learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../teaching-dossier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Teaching Dossier</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research Effectiveness</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#curriculum-vitae" id="toc-curriculum-vitae" class="nav-link active" data-scroll-target="#curriculum-vitae">Curriculum Vitae</a>
  <ul class="collapse">
  <li><a href="#education" id="toc-education" class="nav-link" data-scroll-target="#education">Education</a></li>
  <li><a href="#certifications" id="toc-certifications" class="nav-link" data-scroll-target="#certifications">Certifications</a></li>
  <li><a href="#employment-history" id="toc-employment-history" class="nav-link" data-scroll-target="#employment-history">Employment History</a></li>
  <li><a href="#refereed-journal-articles" id="toc-refereed-journal-articles" class="nav-link" data-scroll-target="#refereed-journal-articles">Refereed Journal Articles</a></li>
  <li><a href="#forthcoming" id="toc-forthcoming" class="nav-link" data-scroll-target="#forthcoming">Forthcoming</a></li>
  <li><a href="#refereed-proceedings" id="toc-refereed-proceedings" class="nav-link" data-scroll-target="#refereed-proceedings">Refereed Proceedings</a></li>
  <li><a href="#refereed-presentations" id="toc-refereed-presentations" class="nav-link" data-scroll-target="#refereed-presentations">Refereed Presentations</a></li>
  <li><a href="#non-refereed-presentations" id="toc-non-refereed-presentations" class="nav-link" data-scroll-target="#non-refereed-presentations">Non-Refereed Presentations</a></li>
  <li><a href="#media" id="toc-media" class="nav-link" data-scroll-target="#media">Media</a></li>
  <li><a href="#research-dissemination" id="toc-research-dissemination" class="nav-link" data-scroll-target="#research-dissemination">Research Dissemination</a></li>
  <li><a href="#research-funding" id="toc-research-funding" class="nav-link" data-scroll-target="#research-funding">Research Funding</a></li>
  <li><a href="#teaching-activities" id="toc-teaching-activities" class="nav-link" data-scroll-target="#teaching-activities">Teaching Activities</a></li>
  <li><a href="#curriculum-development-projects" id="toc-curriculum-development-projects" class="nav-link" data-scroll-target="#curriculum-development-projects">Curriculum Development Projects</a></li>
  <li><a href="#service" id="toc-service" class="nav-link" data-scroll-target="#service">Service</a>
  <ul class="collapse">
  <li><a href="#reviewer" id="toc-reviewer" class="nav-link" data-scroll-target="#reviewer">Reviewer</a></li>
  <li><a href="#committees" id="toc-committees" class="nav-link" data-scroll-target="#committees">Committees</a></li>
  </ul></li>
  <li><a href="#awards" id="toc-awards" class="nav-link" data-scroll-target="#awards">Awards</a></li>
  <li><a href="#professional-learning" id="toc-professional-learning" class="nav-link" data-scroll-target="#professional-learning">Professional Learning</a></li>
  </ul></li>
  <li><a href="#research-plan" id="toc-research-plan" class="nav-link" data-scroll-target="#research-plan">Research Plan</a>
  <ul class="collapse">
  <li><a href="#funding" id="toc-funding" class="nav-link" data-scroll-target="#funding">Funding</a></li>
  <li><a href="#knowledge-mobilization" id="toc-knowledge-mobilization" class="nav-link" data-scroll-target="#knowledge-mobilization">Knowledge Mobilization</a></li>
  <li><a href="#graduate-student-development" id="toc-graduate-student-development" class="nav-link" data-scroll-target="#graduate-student-development">Graduate Student Development</a></li>
  </ul></li>
  <li><a href="#teaching-statement" id="toc-teaching-statement" class="nav-link" data-scroll-target="#teaching-statement">Teaching Statement</a>
  <ul class="collapse">
  <li><a href="#philosophy-of-teaching-and-learning" id="toc-philosophy-of-teaching-and-learning" class="nav-link" data-scroll-target="#philosophy-of-teaching-and-learning">Philosophy of Teaching and Learning</a>
  <ul class="collapse">
  <li><a href="#who-learners-are" id="toc-who-learners-are" class="nav-link" data-scroll-target="#who-learners-are">Who Learners Are</a></li>
  <li><a href="#what-teachers-do" id="toc-what-teachers-do" class="nav-link" data-scroll-target="#what-teachers-do">What Teachers Do</a></li>
  <li><a href="#how-teachers-know-what-learners-know" id="toc-how-teachers-know-what-learners-know" class="nav-link" data-scroll-target="#how-teachers-know-what-learners-know">How Teachers Know What Learners Know</a></li>
  </ul></li>
  <li><a href="#teaching-interests" id="toc-teaching-interests" class="nav-link" data-scroll-target="#teaching-interests">Teaching Interests</a></li>
  <li><a href="#teaching-effectiveness" id="toc-teaching-effectiveness" class="nav-link" data-scroll-target="#teaching-effectiveness">Teaching Effectiveness</a></li>
  <li><a href="#efforts-to-improve-teaching" id="toc-efforts-to-improve-teaching" class="nav-link" data-scroll-target="#efforts-to-improve-teaching">Efforts to Improve Teaching</a></li>
  <li><a href="#pedagogical-innovations" id="toc-pedagogical-innovations" class="nav-link" data-scroll-target="#pedagogical-innovations">Pedagogical Innovations</a></li>
  </ul></li>
  <li><a href="#publications-focused-on-assessment-and-evaluation" id="toc-publications-focused-on-assessment-and-evaluation" class="nav-link" data-scroll-target="#publications-focused-on-assessment-and-evaluation">Publications Focused on Assessment and Evaluation</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ont-tech-letter.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="colin-madland" class="level1 unnumbered unlisted">
<h1 class="unnumbered unlisted">Colin Madland</h1>
<p>1449 Green Bay Road West Kelowna, BC Canada</p>
<p>October 8, 2025</p>
<p>Search Committee Chair<br>
Frazer Faculty of Education<br>
Ontario Tech University</p>
<p><strong>RE: Application for the Position of Assistant Professor, Assessment and Evaluation</strong></p>
<p>Dear Search Committee,</p>
<p>Thank you for taking the time to review my application package for this role. I know it is a time intensive process, having led and been a part of numerous hiring committees. Please find enclosed my application to be considered for the Assistant Professor of Assessment and Evaluation position.</p>
<p>The following pages demonstrate that I have met the requirements to be successful in this position, including: experience in qualitative, quantitative and mixed methods research, an emerging record of high-quality publications, a history of successful funding applications, committment to exemplary teaching and graduate supervision, the ability to cultivate equitable, diverse, and inclusive research partnerships, and a history of open knowledge mobilization.</p>
<p>Having completed my Master of Education (Distance Education) at Athabasca University and doctoral coursework at the University of Victoria (in addition to courses from the University of British Columbia and the University of Alberta as part of the Western Dean’s Agreement), I have had an excellent foundation for advancing my research program in technology-integrated learning and assessment. My academic research has centred around assessment in technology-integrated environments, with a special focus on inclusive and relational practices to support all learners, and especially underserved populations (e.g., Indigenous, remote).</p>
<p>A key output from my dissertation research was the Technology-integrated Assessment Framework (TIAF) <span class="citation" data-cites="madlandDevelopingTechnologyIntegratedAssessment2024">(<a href="#ref-madlandDevelopingTechnologyIntegratedAssessment2024" role="doc-biblioref">Madland et al. 2024</a>)</span>. The framework highlights the importance of integrating Indigenous knowledge systems and methodologies as well as a pedagogy of care in technology-integrated learning environments beginning during the instructional/learning design phase of course development. The <em>Research Plan</em> section below highlights key areas of research that flow from the TIAF, including operationalizing the framework for use as a tool to guide individual instructors or departments in exploring their approaches to technology-integrated assessment in higher education. Also included in this document are links to two recently published articles on the TIAF and two other outputs related to my scholarly work in Indigenous learning contexts and a proceeding that resulted from an experience I had with automated computer vision software.</p>
<p>The <em>Teaching Statement</em> section documents the courses I have taught since 2019, when I began my PhD studies. All of the courses that I have taught at the higher education level have been fully online and I completed my MEd in Distance Education through Athabasca University. Additionally, I have been employed full time since 2010 supporting online instructors, learners, instructional designers, course production professionals and media creators in creating, producing and delivering high-impact online learning experiences. In my personal assessment practice, I focus on relational approaches, such as regular oral assessment conversations and communication of progress using a proficiency scale. These methods prioritize equitable learning and transformation rather than transactional compliance.</p>
<!-- ## Contact Information for Three Referees -->
<!-- Dr. Valerie Irvine (Ph.D. Supervisor)  
Director, Technology Integration and Evaluation Research Lab  
University of Victoria  
virvine@uvic.ca -->
<!-- Dr. Griff Richards (Retired; M.Ed. supervisor)  
Athabasca University  
jgriffr@gmail.com -->
<!-- Dr. Micheal Paskevicius 
Associate Professor, Educational Technology  
University of Victoria  
mpaskevi@uvic.ca -->
<p>Thank you again for taking the time to review my application package. If you have any questions, please do not hesitate to reach out via email (cmadland@uvic.ca) or by phone (1-778-257-3533).</p>
<p>Sincerely,</p>
<p>Colin Madland</p>
<div style="page-break-after: always;"></div>
</section>
<section id="curriculum-vitae" class="level1">
<h1>Curriculum Vitae</h1>
<section id="education" class="level2">
<h2 class="anchored" data-anchor-id="education">Education</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Degree</th>
<th style="text-align: left;">Field</th>
<th style="text-align: left;">Institution</th>
<th style="text-align: left;">Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ph.D.</td>
<td style="text-align: left;">Technology-Integrated Assessment</td>
<td style="text-align: left;">University of Victoria</td>
<td style="text-align: left;">2026</td>
</tr>
<tr class="even">
<td style="text-align: left;">M.Ed.</td>
<td style="text-align: left;">Distance Education</td>
<td style="text-align: left;">Athabasca University</td>
<td style="text-align: left;">2014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B.Ed.</td>
<td style="text-align: left;">Physical Education</td>
<td style="text-align: left;">University of Lethbridge</td>
<td style="text-align: left;">2001</td>
</tr>
<tr class="even">
<td style="text-align: left;">B.A.</td>
<td style="text-align: left;">Physical Education</td>
<td style="text-align: left;">Trinity Western University</td>
<td style="text-align: left;">1997</td>
</tr>
</tbody>
</table>
<!--
\* I completed candidacy in 2022 and have since published 2 of 3 papers for my dissertation. The third paper is in process and I expect to be complete by the summer of 2025.

\*\*Thesis: *Structured Student Interactions in Online Distance Education: Exploring the Study Buddy Activity* <http://hdl.handle.net/10791/47>
-->
</section>
<section id="certifications" class="level2">
<h2 class="anchored" data-anchor-id="certifications">Certifications</h2>
<ul>
<li>British Columbia Ministry of Education Teacher Regulation Branch
<ul>
<li>Professional Certificate #L178396</li>
</ul></li>
<li>Alberta Education
<ul>
<li>Permanent Professional Certificate #254651U</li>
</ul></li>
</ul>
</section>
<section id="employment-history" class="level2">
<h2 class="anchored" data-anchor-id="employment-history">Employment History</h2>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th>Dates</th>
<th>Position, Employer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024 -</td>
<td>Director, Technology-integrated Learning and Assessment, Trinity Western University</td>
</tr>
<tr class="even">
<td>2016 - 2024</td>
<td>Manager of Online Learning and Instructional Technologies, Trinity Western University</td>
</tr>
<tr class="odd">
<td>2019 -</td>
<td>Sessional Instructor, Trinity Western University</td>
</tr>
<tr class="even">
<td>2019 - 2022</td>
<td>Sessional Instructor, University of Victoria</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>Coordinator for Educational Technologies, Thompson Rivers University (Sessional )</td>
</tr>
<tr class="even">
<td>2015 - 2017</td>
<td>Open Education Research Fellow</td>
</tr>
<tr class="odd">
<td>2010 - 2016</td>
<td>E-Learning Facilitator, Thompson Rivers University</td>
</tr>
<tr class="even">
<td>2009 - 2013</td>
<td>Research Assistant, Athabasca University</td>
</tr>
<tr class="odd">
<td>2007 - 2010</td>
<td>High School Teacher and Athletic Director, St.&nbsp;Ann’s Academy</td>
</tr>
<tr class="even">
<td>2005 - 2007</td>
<td>English Teacher, Ogaki and Nagoya, Japan</td>
</tr>
</tbody>
</table>
</section>
<section id="refereed-journal-articles" class="level2">
<h2 class="anchored" data-anchor-id="refereed-journal-articles">Refereed Journal Articles</h2>
<ul>
<li><strong>Madland, C.</strong>, Irvine, V., DeLuca, C., &amp; Bulut, O. (2024a). Developing the Technology-Integrated Assessment Framework. <em>The Open/Technology in Education, Society, and Scholarship Association Journal, 4</em>(1), 1–19. <a href="https://doi.org/10.18357/otessaj.2024.4.1.63" class="uri">https://doi.org/10.18357/otessaj.2024.4.1.63</a></li>
<li><strong>Madland, C.</strong>, Irvine, V., DeLuca, C., &amp; Bulut, O. (2024b). Technology-Integrated Assessment: A Literature Review. <em>The Open/Technology in Education, Society, and Scholarship Association Journal, 4</em>(1), 1–48. <a href="https://doi.org/10.18357/otessaj.2024.4.1.57" class="uri">https://doi.org/10.18357/otessaj.2024.4.1.57</a></li>
<li><strong>Madland, C.</strong>, &amp; Richards, G. (2016). Enhancing Student-Student Online Interaction: Exploring the Study Buddy Peer Review Activity. <em>International Review of Research in Open and Distance Learning, 17</em>(3). <a href="https://doi.org/10.19173/irrodl.v17i3.2179" class="uri">https://doi.org/10.19173/irrodl.v17i3.2179</a></li>
</ul>
</section>
<section id="forthcoming" class="level2">
<h2 class="anchored" data-anchor-id="forthcoming">Forthcoming</h2>
<ul>
<li><strong>Madland, C.</strong>, Irvine, V., Bulut, O., &amp; DeLuca, C. (In preparation). Exploring the Factor Structure of the Technology-Integrated Assessment Framework.</li>
<li><strong>Madland, C.</strong>, Irvine, V., Bulut, O., &amp; DeLuca, C. (In preparation). Impact of genAI Policies and Practices on Learners’ Experiences of Care in Higher Education Assessment. <!-- - Cui, H., Irvine, V., Miller, M., & **Madland, C.** (In Preparation). Creating Capacity for Digital Transformation of Education: Mode and Disciplinary Barriers in the Development of Highly Qualified Personnel. *Canadian Journal of Learning and Technology*. --> <!-- - Irvine, V., Paskevicius, M., **Madland, C.**, McCue, R., & Roberts, V. (In Preparation). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. *Open Praxis*.  --></li>
</ul>
</section>
<section id="refereed-proceedings" class="level2">
<h2 class="anchored" data-anchor-id="refereed-proceedings">Refereed Proceedings</h2>
<ul>
<li><strong>Madland, C.</strong>, Irvine, V., DeLuca, C., &amp; Bulut, O. (2024, June). Evolving our understanding of technology-integrated assessment: A review of the literature and development of a new framework. <em>Open/Technology in Education, Society, and Scholarship Association at Congress of the Social Sciences and Humanities</em>, Montreal, QC, CA. <a href="https://doi.org/10.18357/otessac.2024.4.1.393" class="uri">https://doi.org/10.18357/otessac.2024.4.1.393</a></li>
<li>Cui, H., Irvine, V., Miller, M., &amp; <strong>Madland, C.</strong> (2024). Creating Capacity for Digital Transformation of Education: Mode and Disciplinary Barriers in the Development of Highly Qualified Personnel. <em>Proceedings of the Open/Technology in Education, Society, and Scholarship Association Conference. Open/Technology in Education, Society, and Scholarship Association Conference,</em> Montréal, QC. <a href="https://doi.org/10.18357/otessac.2024.4.1.421" class="uri">https://doi.org/10.18357/otessac.2024.4.1.421</a></li>
<li>Irvine, V., Paskevicius, M., <strong>Madland, C.</strong>, McCue, R., &amp; Roberts, V. (2022). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. <em>The Open/Technology in Education, Society, and Scholarship Association Conference, 2</em>(1), 1–9. <a href="https://doi.org/10.18357/otessac.2022.2.1.419" class="uri">https://doi.org/10.18357/otessac.2022.2.1.419</a></li>
<li><strong>Madland, C.</strong>, Ofosuhene, M., &amp; Adkins, J. (2022). Digital Platforms and Algorithmic Erasure: What are the Implications? <em>Open/Technology in Education, Society, and Scholarship Association at Congress of the Social Sciences and Humanities</em>, Online. <a href="https://doi.org/10.18357/otessac.2022.2.1.137" class="uri">https://doi.org/10.18357/otessac.2022.2.1.137</a></li>
<li>Irvine, V., Paskevicius, M., <strong>Madland, C</strong>., McCue, R., &amp; Roberts, V. (2022). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. Proceedings of the Open/Technology in Education, Society, and Scholarship Association Conference, 1–3. <a href="https://doi.org/10.18357/otessac.2022.2.1.419" class="uri">https://doi.org/10.18357/otessac.2022.2.1.419</a></li>
<li><strong>Madland, C.</strong>, &amp; Restoule, J.-P. (2021). Self-Determination in Indigenous Online Education. <em>The Open/Technology in Education, Society, and Scholarship Association Conference, 1</em> (1), 1–7. <a href="https://doi.org/10.18357/otessac.2021.1.1.147" class="uri">https://doi.org/10.18357/otessac.2021.1.1.147</a></li>
</ul>
</section>
<section id="refereed-presentations" class="level2">
<h2 class="anchored" data-anchor-id="refereed-presentations">Refereed Presentations</h2>
<ul>
<li><strong>Madland, C.</strong>, &amp; Mitchell, J. (2025, June 5). Assessment for Equity: Openness and DEI in your Grading Architecture [50-min Workshop]. <em>Open/Technology in Education, Society, and Scholarship Association Conference, Victoria, BC.</em> <a href="https://cmadland.github.io/slides/posts/otessa25-grading/#/title-slide" class="uri">https://cmadland.github.io/slides/posts/otessa25-grading/#/title-slide</a></li>
<li><strong>Madland, C.</strong>, Irvine, V., DeLuca, C., &amp; Bulut, O. (2025, June 6). Technology-integrated Assessment Scale [20-min Presentation]. <em>Open/Technology in Education, Society, and Scholarship Association Conference, Victoria, BC.</em> <a href="https://cmadland.github.io/slides/posts/otessa25-scale/#/title-slide" class="uri">https://cmadland.github.io/slides/posts/otessa25-scale/#/title-slide</a></li>
<li><strong>Madland, C.</strong>, Irvine, V., DeLuca, C., &amp; Bulut, O. (2024, June). Evolving our understanding of technology-integrated assessment: A review of the literature and development of a new framework. <em>Open/Technology in Education, Society, and Scholarship Association</em>, Montreal, QC, CA. <a href="https://cmadland.github.io/blog/posts/deck-otessa24/#/title-slide" class="uri">https://cmadland.github.io/blog/posts/deck-otessa24/#/title-slide</a></li>
<li><strong>Madland, C.</strong> (2023, June). Research? Which Research? Technology, Assessment, and Higher Education in Tension. <em>Open/Technology in Education, Society, and Scholarship Association</em>, Online.</li>
<li><strong>Madland, C.</strong> (2022, May). Assessment and Digital Technology in Higher Education: A Review of the Literature. <em>Open/Technology in Education, Society, and Scholarship Association</em>, Online. <a href="https://cmadland.github.io/decks/otessa22---assessment-and-digital-technology-in-higher-education.html#otessa22---assessment-and-digital-technology-in-higher-education" class="uri">https://cmadland.github.io/decks/otessa22---assessment-and-digital-technology-in-higher-education.html#otessa22---assessment-and-digital-technology-in-higher-education</a></li>
<li>Irvine, V., Paskevicius, M., <strong>Madland, C.</strong>, McCue, R., Roberts, V. (2022, May). Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners. OTESSA 2022, Online. <a href="https://otessa.github.io/2022/wedesday-may-18-2022.html#parallel-session-11.1-transitions-of-online-learning-and-teaching-pse-open" class="uri">https://otessa.github.io/2022/wedesday-may-18-2022.html#parallel-session-11.1-transitions-of-online-learning-and-teaching-pse-open</a></li>
<li>Marjanovic, K., Golland, B., <strong>Madland, C.</strong> (2022, May). Share Access! Using Bookdown to Remove Barriers and Open Up Learning. OTESSA 2022, Online. <a href="https://otessa.github.io/2022/friday-may-20-2022.html#share-access-using-bookdown-to-remove-barriers-and-open-up-learning" class="uri">https://otessa.github.io/2022/friday-may-20-2022.html#share-access-using-bookdown-to-remove-barriers-and-open-up-learning</a></li>
<li><strong>Madland, C.</strong>, Ofosuhene, M., and Adkins, J., (2022, May). Digital platforms and algorithmic erasure: What are the implications? OTESSA 2022, Online. <a href="https://otessa.github.io/2022/tuesday-may-17-2022.html#digital-platforms-and-algorithmic-erasure-what-are-the-implications-practice-oriented" class="uri">https://otessa.github.io/2022/tuesday-may-17-2022.html#digital-platforms-and-algorithmic-erasure-what-are-the-implications-practice-oriented</a></li>
<li><strong>Madland, C.</strong> (2021, September). Assessment Approaches in Higher Education. Let’s Talk about Teaching, Victoria, BC.</li>
<li>Clark Gray, B., &amp; <strong>Madland, C.</strong> (2021, June). Resisting Surveillance Technology. OTESSA 2021, Online. <a href="https://otessa.org/2021/abstracts/resisting-surveillance-technology/" class="uri">https://otessa.org/2021/abstracts/resisting-surveillance-technology/</a></li>
<li><strong>Madland, C.</strong>, &amp; James, H. (2021, June). Experiencing a cognitive apprenticeship in the context of co-designing and co-teaching an undergraduate course. OTESSA 2021, Online. <a href="https://otessa.org/2021/abstracts/experiencing-a-cognitive-apprenticeship-in-the-context-of-co-designing-and-co-teaching-an-undergraduate-course/" class="uri">https://otessa.org/2021/abstracts/experiencing-a-cognitive-apprenticeship-in-the-context-of-co-designing-and-co-teaching-an-undergraduate-course/</a></li>
<li><strong>Madland, C.</strong> (2021, May). Humanizing Assessment in Online Higher Education. OTESSA 2021, Online. <a href="https://otessa.org/2021/abstracts/humanizing-assessment-in-online-higher-education/" class="uri">https://otessa.org/2021/abstracts/humanizing-assessment-in-online-higher-education/</a></li>
<li><strong>Madland, C.</strong> (2021, May). Indigenous Digital Self-Determination. OTESSA 2021, Online. <a href="https://otessa.org/2021/abstracts/indigenous-digital-self-determination/" class="uri">https://otessa.org/2021/abstracts/indigenous-digital-self-determination/</a></li>
<li>Chan, K., Irvine, V., &amp; <strong>Madland, C.</strong> (2020, July). Decentralized Synchronous Learning Pods For Learner Discourse and Community-Building: An Alternative to Breakout Rooms. <em>Let’s Talk about Teaching, Victoria, BC.</em></li>
<li>Irvine, V., James, H., <strong>Madland, C.</strong>, &amp; McCue, R. (2020, July). Teaching in the Open: Supporting Open Access Designs for Social Justice. <em>Let’s Talk about Teaching, Victoria, BC.</em></li>
<li>James, H., &amp; <strong>Madland, C.</strong> (2020, July). Co-Designing and Co-Teaching an Online Course. <em>Let’s Talk about Teaching, Victoria, BC.</em></li>
<li><strong>Madland, C.</strong>, &amp; Irvine, V. (2020, April 17). Self-Determination in Indigenous Online Education [Roundtable Session]. AERA Annual Meeting, San Francisco, CA. (Conference Canceled). <a href="http://tinyurl.com/vp8h3q8" class="uri">http://tinyurl.com/vp8h3q8</a></li>
<li><strong>Madland, C.</strong> (2019, June). Indigenous and Open Education: A contradiction? CSSHE Conference, Vancouver, BC.</li>
<li><strong>Madland, C.</strong> (2017). Flexible Infrastructure to Support the Design and Delivery of Online Learning. ICDE World Conference for Online Learning, Toronto.</li>
<li><strong>Madland, C.</strong> (2016, November). The Open Advantage. Open Education, Richmond, VA.</li>
<li>Hendricks, C., Jhangiani, R., &amp; <strong>Madland, C.</strong> (2016, March). Experiences, perceptions, and outcomes of BC students using open textbooks: Research from the BC OER Research Fellows. BCcampus Festival of Learning.</li>
<li><strong>Madland, C.</strong> (2016a, February). Building Trust and Community with Initiative Tasks. Teaching Practices Colloquium, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2016, February). Communities of Inquiry to Ignite Learning. Teaching Practices Colloquium, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2016, April). Enhancing Learning through OER and Open Platforms. OER16, Edinburgh, Scotland.</li>
<li><strong>Madland, C.</strong> (2016, April). Exploring the Remix Hypothesis. Open Education Global Conference, Krakow, Poland.</li>
<li><strong>Madland, C.</strong> (2015, November). Open and Connected Faculty Development. Open Education, Vancouver, BC.</li>
<li><strong>Madland, C.</strong> (2014, February). Structured Student Interactions. Teaching Practices Colloquium, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2014, May). Encouraging Deeper Approaches to Learning. Open Learning Faculty Members Workshop, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2014, May). Structured Student Interactions. CNIE Conference, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2013, September). Structuring Student Interactions in Online Distance Learning: Exploring the Study Buddy Activity. Athabasca University Graduate Students’ Conference, Edmonton, AB.</li>
<li><strong>Madland, C.</strong> (2012, February). Engaging Students with Video. Teaching Practices Colloquium, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2012, May). Online Faculty Development. Southern Alberta Institute of Technology Faculty Showcase, Calgary, AB.</li>
</ul>
</section>
<section id="non-refereed-presentations" class="level2">
<h2 class="anchored" data-anchor-id="non-refereed-presentations">Non-Refereed Presentations</h2>
<ul>
<li><strong>Madland, C.</strong> (2012, May). Outside the Box Feedback with Adobe Acrobat. Open Learning Faculty Members Workshop, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2011, October). Thinking Despite the Box: Designing Interaction in Blackboard. Teaching with Technology Series, Kamloops, BC.</li>
<li><strong>Madland, C.</strong> (2010, October). Twitter in Higher Education. Teaching with Technology Series, Kamloops, BC.</li>
</ul>
</section>
<section id="media" class="level2">
<h2 class="anchored" data-anchor-id="media">Media</h2>
<ul>
<li>Krinsky, S., &amp; Bosley, R. (October 8, 2024). Alt Grading in Physical Education, Canadian Grading Reforms, and Technology-Integrated Assessment: An Interview with Colin Madland (No.&nbsp;65) [Podcast]. <a href="https://thegradingpod.com/episodes/65-alt-grading-in-physical-education-canadian-grading-reforms-and-technology-integrated-assessment-an-interview-with-colin-madland/" class="uri">https://thegradingpod.com/episodes/65-alt-grading-in-physical-education-canadian-grading-reforms-and-technology-integrated-assessment-an-interview-with-colin-madland/</a></li>
<li>Greene, T. (2020). Valerie Irvine and Colin Madland [Broadcast]. [Podcast]. <a href="https://www.spreaker.com/episode/valerie-irvine-and-colin-madland--23026170" class="uri">https://www.spreaker.com/episode/valerie-irvine-and-colin-madland--23026170</a></li>
</ul>
</section>
<section id="research-dissemination" class="level2">
<h2 class="anchored" data-anchor-id="research-dissemination">Research Dissemination</h2>
<ul>
<li>“Technology-Integrated Assessment in Higher Education”; Kigali, Rwanda; Uganda; and Pan-Africa Christian University, Nairobi, Kenya, November 2024</li>
<li>“Self-Paced Learning in Higher Education”, Pan-Africa Christian University, Nairobi, Kenya, May 2023</li>
<li>“What is Assessment”, TWU Faculty Professional Learning. March 2023 <a href="https://cmadland.github.io/decks/twu-faculty-professional-learning.html" class="uri">https://cmadland.github.io/decks/twu-faculty-professional-learning.html</a>.</li>
</ul>
</section>
<section id="research-funding" class="level2">
<h2 class="anchored" data-anchor-id="research-funding">Research Funding</h2>
<ul>
<li>BCcampus Research Fellowship, 2022 ($6000)</li>
<li>University of Victoria Graduate Student Award, September 2019 ($5000)</li>
<li>University of Victoria Graduate Student Award, September 2018 ($5000)</li>
<li>TRU Open Learning Presentation Fund, April 2016 ($5000)</li>
<li>Open Education Resources Research Fellow, Open Education Group, 2015-16 (5000 USD)</li>
<li>Athabasca University Tim Byrne Memorial Scholarship (for academic excellence along with an outstanding thesis or project), nominated by the Centre for Distance Education, June 2014. ($1000)</li>
<li>Athabasca University Student Travel Award, September 2013. ($800)</li>
<li>Athabasca University Graduate Student Mission Critical Research Fund, April 2013. ($420)</li>
<li>Athabasca University Access to Research Tools, April 2013. ($300)</li>
</ul>
</section>
<section id="teaching-activities" class="level2">
<h2 class="anchored" data-anchor-id="teaching-activities">Teaching Activities</h2>
<p>Undergraduate and <strong>Graduate</strong> - All courses and sections were taught fully online.</p>
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Year</th>
<th>Course</th>
<th style="text-align: center;">Title</th>
<th style="text-align: center;">Credit Hours/Units</th>
<th style="text-align: center;">Students</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Summer 2019</td>
<td>EDCI 335</td>
<td style="text-align: center;">Learning Design</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">37</td>
</tr>
<tr class="even">
<td style="text-align: center;">Summer 2019</td>
<td>EDCI 339</td>
<td style="text-align: center;">Open and Distributed Learning</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Summer 2019</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Summer 2020</td>
<td>EDCI 335</td>
<td style="text-align: center;">Learning Design</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">56</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Summer 2020</td>
<td>EDCI 339</td>
<td style="text-align: center;">Open and Distributed Learning</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">59</td>
</tr>
<tr class="even">
<td style="text-align: center;">Summer 2020</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Fall 2020</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: center;">Spring 2021</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Summer 2021</td>
<td>EDCI 335</td>
<td style="text-align: center;">Learning Design</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">40</td>
</tr>
<tr class="even">
<td style="text-align: center;">Fall 2021</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7 (All in Nigeria)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Fall 2021</td>
<td>EDCI 335</td>
<td style="text-align: center;">Learning Design</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">41</td>
</tr>
<tr class="even">
<td style="text-align: center;">Spring 2022</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Summer 2022</td>
<td>EDCI 338</td>
<td style="text-align: center;">Social Media and Personalized Learning</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">39</td>
</tr>
<tr class="even">
<td style="text-align: center;">Spring 2023</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1 (DS)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Fall 2023</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6 (4 in Nigeria)</td>
</tr>
<tr class="even">
<td style="text-align: center;">Fall 2023</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Fall 2024</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Fall 2024</td>
<td>LDRS 463</td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Summer 2025</td>
<td><strong>LDRS 663</strong></td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">Summer 2025</td>
<td>LDRS 463</td>
<td style="text-align: center;">Transformational Blended Learning</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</section>
<section id="curriculum-development-projects" class="level2">
<h2 class="anchored" data-anchor-id="curriculum-development-projects">Curriculum Development Projects</h2>
<ul>
<li>LDRS 101 - Learning in a Digital World</li>
<li>LDRS 663 - Transformational Blended Learning</li>
<li>EDCI 335 - Learning Design</li>
<li>EDCI 339 - Distributed and Open Learning</li>
<li>Teaching Online Effectively (TOnE)</li>
<li>Online Teaching and Learning</li>
<li>Online Facilitation Skills for Student Learning, Engagement, and Retention</li>
<li>Course Management Strategies</li>
<li>Online Student Success</li>
</ul>
</section>
<section id="service" class="level2">
<h2 class="anchored" data-anchor-id="service">Service</h2>
<section id="reviewer" class="level3">
<h3 class="anchored" data-anchor-id="reviewer">Reviewer</h3>
<ul>
<li>Open/Technology in Education, Society, and Scholarship Association (OTESSA) Conference</li>
<li>Open/Technology in Education Society, and Scholarship Association (OTESSA) Journal,</li>
<li>International Review of Research in Open and Distributed Learning (IRRODL),</li>
<li>Research in Learning Technology (ISSOTL)</li>
<li>Teaching &amp; Learning Inquiry</li>
<li>International Journal of E-Learning and Distance Education</li>
</ul>
</section>
<section id="committees" class="level3">
<h3 class="anchored" data-anchor-id="committees">Committees</h3>
<ul>
<li>Founding Board Member, <a href="https://otessa.org">Open/Technology in Education, Society, and Scholarship Association (OTESSA)</a>, 2019-present</li>
<li>Faculty Professional Learning Committee, Trinity Western University, 2016-present</li>
<li>Board of Directors, Canadian Network for Innovation in Education (CNIE), 2016-2018</li>
<li>Chair, Thompson Rivers University Graduate Studies Committee of Senate, November 2015-April 2016</li>
<li>Thompson Rivers University Graduate Studies Committee of Senate, November 2012 - November 2015</li>
<li>Academic Planning and Priorities Committee of Senate, October 2015-April 2016</li>
</ul>
</section>
</section>
<section id="awards" class="level2">
<h2 class="anchored" data-anchor-id="awards">Awards</h2>
<ul>
<li>Outstanding Service Award from Thompson Rivers University Open Learning, September 2012.</li>
</ul>
</section>
<section id="professional-learning" class="level2">
<h2 class="anchored" data-anchor-id="professional-learning">Professional Learning</h2>
<ul>
<li>Coaching for Leaders, Smart + Savvy and Associates (2018)</li>
<li><a href="https://www.tru.ca/intercultural/inventory.html">Interculturalizing the Curriculum</a>, Thompson Rivers University (2015)</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="research-plan" class="level1">
<h1>Research Plan</h1>
<p>Educational assessment is at the heart of robust formal education systems and has been deeply impacted by both COVID-19 and by the broad emergence of generative artificial intelligence (genAI). My research program is focused, in the short-term, on quantitatively refining and operationalizing the TIAF in the context of emerging technologies, such as genAI and artificial/virtual reality (AR/VR). In the longer term, there is much work to be done to operationalize the refined TIAF by continuing to build a scale to be used to help individual educators, centres for teaching and learning, scholars of teaching and learning, and/or any other interested stakeholder to explore and understand the impacts of emerging technologies on assessment design and practice, and, by extension, to transform assessment practice in formal digital learning environments. The potential for transformative impact on education systems by paying attention to technology-integrated assessment is significant, as Ramsden claims, “assessment always defines the actual curriculum” <span class="citation" data-cites="ramsdenLearningTeachHigher2003">(<a href="#ref-ramsdenLearningTeachHigher2003" role="doc-biblioref">2003</a>)</span>. I believe that transforming technology-integrated assessment practices is one of the most powerful levers we have in the drive to enable access to high quality higher education for all learners.</p>
<p>The TIAF comprises four primary constructs (assessment purpose, duty of care, technology acceptance, and measurement), each capable of supporting robust interdisciplinary quantitative, qualitative, and mixed-method investigations. Each of the four constructs is grounded in the 5 Rs of Indigenous education (respect, relevance, reciprocity, responsibility, and relationships) <span class="citation" data-cites="tessaro2018">(<a href="#ref-tessaro2018" role="doc-biblioref">Tessaro et al. 2018</a>)</span>, making the TIAF a valuable tool for removing barriers to Indigenous learners and communities.</p>
<p>Questions that arise from the <em>assessment purpose</em> construct include investigating the impacts of AI use on the balance of assessment of/for/as learning in higher education practice. More specifically, emerging technologies including genAI and AR/VR, have provided opportunity for instructors to focus more on the <em>process</em> of learning and assessment for/as learning compared to the <em>products</em> of learning. The <em>duty of care</em> construct provides myriad opportunities for investigations into the ethics of genAI or AR/VR use and the ways in which it is important to prioritize human characteristics and relationships in education. Note especially the differential impacts on racialized learners and their challenges with using AI-powered remote proctoring services during the COVID-19 pandemic (see my proceeding that highlights my viral experience with this issue <span class="citation" data-cites="madlandDigitalPlatformsAlgorithmic2022">(<a href="#ref-madlandDigitalPlatformsAlgorithmic2022" role="doc-biblioref">Madland, Ofosuhene, and Adkins 2022</a>)</span>). At the same time, there are notable benefits for equity-deserving groups (e.g.&nbsp;neurodivergent learners) who may be able to leverage boutique, privacy-protecting genAI models to preview and refine their work prior to submission to an instructor. Duty of care is especially important to prioritize in Indigenous learning contexts where there is a long history of exploitation, extraction, and extermination in the context of education (see my proceeding based on exploring this issue <span class="citation" data-cites="madlandSelfDeterminationIndigenousOnline2021">(<a href="#ref-madlandSelfDeterminationIndigenousOnline2021" role="doc-biblioref">Madland and Restoule 2021</a>)</span>). The <em>technology acceptance</em> construct leads to questions about managing technological and pedagogical change in contexts with a focus on technology adoption by instructors. Lasting transformation of educational systems requires deep and careful work in managing change. My work as Director of Technology-integrated Learning and Assessment has given me clear insight and direct experience in managing and transforming educational systems and technological infrastructure at an enterprise level. This experience provides crucial context for my research into technology acceptance and adoption by the full breadth of stakeholders, from learners, to instructors, support staff, and senior administrators and board-level executives. Lastly, the <em>assessment design</em> construct offers many opportunities to consider pedagogical designs and architectures that maximize the impact of quality learning experiences. Too often, universal design for learning (UDL) is an afterthought or an add-on to existing educational and assessment designs, however in this framework, intentional focus is brought to bear on the up-front design of learning environments which are human-centred, equitable, inclusive, and accessible.</p>
<p>The TIAF as a whole and each individual construct described within present rich opportunities for research on learning through transformative digital systems. This wide variety of possible approaches to investigating emerging technologies in open, digital, and distance education leads to multiple opportunities for inclusive quantitative, qualitative, and mixed research collaborations for the benefit of all learners and particularly remote, rural, and Indigenous communities. Further, as the framework is embedded within the 5Rs of Indigenous education, there are multiple possibilities for collaborating with Indigenous scholars to explore these and other questions specific to Indigenous communities as we journey together towards reconciliation and renewal.</p>
<section id="funding" class="level2">
<h2 class="anchored" data-anchor-id="funding">Funding</h2>
<p>As a graduate of the Master of Education program at Athabasca University, I was honored with the Tim Byrne Memorial Scholarship for academic excellence and an outstanding thesis ($1000). I have also received funding from the Open Education Group ($5000 USD), the Thompson Rivers University Presentation Fund ($5000), two University of Victoria Graduate Student awards ($10,000 total), and a BCcampus Research Fellowship ($6000), all in support of my research.</p>
<p>To this point in my career, I have been completing my PhD part-time while engaged in a full-time career in higher education. This has left me with few options for finding funding (e.g, SSHRC funding is only recently available for part-time students, but I am no longer eligible because I am too far along in my program.) I look forward to being able to apply much more of my effort and energy into securing funding, not only through the Tri-Council agencies, but also through government, university, and other external sources. For example, I am privileged to have extensive background with the Technology Integration and Evaluation (TIE) Lab at the University of Victoria where I have been mentored in strategies for securing funding from agencies like the <a href="https://www.innovation.ca/">Canada Foundation for Innovation (CFI)</a> which matches seed funding at a rate of 4:1. This would allow me to leverage start-up funds provided in this position and quadruple the financial impact of that initial funding. My supervisor and mentor used this strategy to raise $1.4 million ($780,000 from CFI, the largest amount at UVic) to support the development of the TIE Lab.</p>
</section>
<section id="knowledge-mobilization" class="level2">
<h2 class="anchored" data-anchor-id="knowledge-mobilization">Knowledge Mobilization</h2>
<p>As a rule, I endeavour to publish all my formal and informal research outputs under an open license and on the web. Below are two examples of these outputs. The first, and informal publication, emerged from my PhD coursework as a visiting student at the University of British Columbia. This publication is a critical family history, an in-depth exploration of one of my ancestors’ emigration from Norway to the USA, then to northern and central Alberta, and finally to British Columbia. The framework for this publication is the history of the treatment of Indigenous peoples throughout North America that opened the way for my great-grandfather to emigrate from Norway.</p>
<p>Madland, C. (2019). <a href="https://cmadland.github.io/cv/timeline.html#critical-family-history">Critical Family History</a> [Blog]. Colin M. Madland.</p>
<p>The second example of knowledge dissemination is related to a viral moment that I and a colleague experienced on Twitter (now defunct). This conference presentation and proceeding described our experiences with the facial detection algorithm on Zoom, which, when posted to Twitter, showed a related problem there.</p>
<p>Madland, C., Ofosuhene, M., &amp; Adkins, J. (2022). <a href="https://doi.org/10.18357/otessac.2022.2.1.137">Digital Platforms and Algorithmic Erasure: What are the Implications?</a> OTESSA Conference 2022. OTESSA 2022, Online.</p>
<p>The original Tweet that set it all off is no longer available on X, but has been <a href="https://bsky.app/profile/cmadtweets.bsky.social/post/3lb5lhuo35c2w">ported to BlueSky</a> where it can be seen without the original context or replies.</p>
</section>
<section id="graduate-student-development" class="level2">
<h2 class="anchored" data-anchor-id="graduate-student-development">Graduate Student Development</h2>
<p>As a PhD candidate, I have not been in a position to mentor or supervise graduate students. That said, I am privileged to have been mentored by distinguished committee members from across Canada: Dr.&nbsp;Valerie Irvine (Supervisor, University of Victoria Director of the Technology Integration and Evaluation Research Lab and President of the Open/Technology in Education, Society, and Scholarship Association), Dr.&nbsp;Christopher DeLuca (Committee Member, Queen’s University Associate Dean of Graduate Studies), and Dr.&nbsp;Okan Bulut (Committee Member, Professor of Measurement, Evaluation and Data Science, University of Alberta and University of Alberta President’s Research Prize Recipient). Each of these mentors has modelled high standards of academic excellence comibined with both support and trust as appropriate. This blend of personal mentoring and adherence to academic excellence has given me a template from which I can build my own practice of mentoring graduate students.</p>
<p>In my role of Director of Technology-Integrated Learning and Assessment, I have the privilege of supervising multiple early career educational technologists, several of whom have since started their journeys through masters and doctoral programs. As such, I have had the opportunity to informally mentor these people as they know that I am nearing completion of my program and seek out my advice. I know from these less formal encounters that each graduate student brings their own experiences, strengths, challenges, and fears to their programs, necessitating a personalized approach for each one.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="teaching-statement" class="level1">
<h1>Teaching Statement</h1>
<section id="philosophy-of-teaching-and-learning" class="level2">
<h2 class="anchored" data-anchor-id="philosophy-of-teaching-and-learning">Philosophy of Teaching and Learning</h2>
<p>In my research and practice of teaching and learning in higher education, I ground my work in three broad principles related to <em>who learners are</em>, <em>what teachers do</em>, and <em>how teachers know what learners know</em>.</p>
<section id="who-learners-are" class="level3">
<h3 class="anchored" data-anchor-id="who-learners-are">Who Learners Are</h3>
<blockquote class="blockquote">
<p>Those who seek to learn to improve themselves and the world around them have inherent dignity and value.</p>
</blockquote>
<p>This principle is expanded in the 5 Rs of Indigenous education <span class="citation" data-cites="tessaro2018">(<a href="#ref-tessaro2018" role="doc-biblioref">Tessaro et al. 2018</a>)</span>: respect, responsibility, relevance, reciprocity, and relationships. The 5 Rs serve as a set of values grounded in the inherent value of all people and the importance of intentional work to foreground the perspectives of equity-deserving groups. When diversity, equity, and inclusion are prioritized and co-created, the entire community of learners benefits from working in an environment where it is safe to be different or wrong. The ultimate goal of education is to empower learners to fully realize <em>their</em> purpose and to flourish in <em>their</em> efforts to improve the world around <em>them</em>.</p>
<p>This principle is reflected in the structure of my courses where learners are always able to make meaningful choices about how their learning will be demonstrated. For example, assignments are always grounded in the course learning outcomes, and they require learners to apply the concepts of the course to their own context. It is the learner who determines relevance, and it is through the relationships developed in the context of the course community that relevant learning is expressed. Respect and reciprocity are demonstrated in the process of co-creating a community of inquiry where all members share the responsibility for the safety and well-being of others. The key to making this all happen is that I host assessment conversations with learners where we meet to discuss their work and come to a mutually agreeable assessment of the quality of their work in light of the course outcomes.</p>
<p>One learner in my class reflected on their experience during LDRS 663 in their final paper (some details are omitted for anonymity):</p>
<blockquote class="blockquote">
<p>Reflecting on these experiences, I’ve come to realize that transformational learning through coaching and facilitation is not simply a collection of tools; it is a deeply transformative mindset rooted in empathy, openness, and a commitment to critically engaging with deeply held beliefs. This mindset has profoundly reshaped my … identity, broadening my understanding of what it means to lead a … community. It challenges the notion of … authority as merely instructive, moving it instead toward a collaborative, relational approach that invites people into a shared journey of growth and exploration. Through this lens, my purpose has evolved into guiding our [community] toward a new understanding of inclusivity—not as a trend, but as an essential … value grounded in love, curiosity, and respect for diverse perspectives.</p>
</blockquote>
</section>
<section id="what-teachers-do" class="level3">
<h3 class="anchored" data-anchor-id="what-teachers-do">What Teachers Do</h3>
<blockquote class="blockquote">
<p>Learning is idealized as a cognitive apprenticeship which supports the process of sense-making in the context of complex ideas.</p>
</blockquote>
<p>We know from Bloom <span class="citation" data-cites="bloom1984">(<a href="#ref-bloom1984" role="doc-biblioref">1984</a>)</span> that the most profound learning experiences occur in the context of sustained discourse between a learner (or maybe two or three) and an instructor (who can sometimes be a peer or other interested observer). This sense-making process must include the learner actively drawing connections between ideas and drawing conclusions that are relevant to their own contexts. Sense-making is often a difficult and tentative process, so it is incumbent on the instructor to allow learners to do the work of learning and to recognize that not all learners will achieve at the same pace. Learners exercise autonomy and agency when they are encouraged to exercise evaluative judgement <span class="citation" data-cites="tai2018">(<a href="#ref-tai2018" role="doc-biblioref">Tai et al. 2018</a>)</span> through the comparison of their own work to the work of both novice and expert others and to the intended learning outcome. The task of assessment is a similar process of the instructor making sense of what the learner has demonstrated in their process and the products of their work.</p>
<p>This principle is realized in my online courses in how I structure discourse, or the conversation around course concepts. Learners are required to demonstrate their process of coming to understand a topic or task, not only submit a final product. A ‘discussion forum’, which may use various platforms such as blogs or social media, in any of my courses is considered to be required, but not graded. The discussion forum is not graded because I want my learners to be free to express tentative or controversial ideas without fear of losing marks. Much like conversations inside the four walls of a brick-and-mortar classroom, which are not graded for accuracy, conversations in an online forum should be considered as works-in-progress as learners make sense of concepts and ideas. For graded assignments, learners are required to submit their working documents in addition to the final, polished version.</p>
<p>An example is this anonymized exerpt from a group project final submission.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/screenshot-sample-doc.png" class="img-fluid figure-img" alt="Screenshot of a portion of a MS Word document showing the process of discussing the task."></p>
<figcaption>Screenshot of a portion of a MS Word document showing the process of discussing the task.</figcaption>
</figure>
</div>
<p>Assessment conversations are a key component of allowing me to come to understand what the learner knows or can do. By having a conversation that includes talking about their working docs and the final product, I can get a clearer picture of the learner’s ability, I can ask clarifying questions in the moment, and the learner can provide valuable context to their work.</p>
</section>
<section id="how-teachers-know-what-learners-know" class="level3">
<h3 class="anchored" data-anchor-id="how-teachers-know-what-learners-know">How Teachers Know What Learners Know</h3>
<blockquote class="blockquote">
<p>If there is an end, it is when the teacher has become unnecessary.</p>
</blockquote>
<p>Coming to know something (learning) is a result of what we do. When learners strive for a cognitive goal, they iterate based on their past knowledge combined with feedback they receive regarding their performance in relation to the goal <span class="citation" data-cites="carless2019 hattie2007">(<a href="#ref-carless2019" role="doc-biblioref">Carless 2019</a>; <a href="#ref-hattie2007" role="doc-biblioref">Hattie and Timperley 2007</a>)</span>. Consequently, learning is inextricably tied to the process of assessing learning. Traditional models of learning require significant time and effort on the part of instructors who are the primary source of feedback in the process. Contrary to that, when a learner is able to generate their own feedback on performance, they are no longer completely reliant on the instructor and can sustain and direct their own learning <span class="citation" data-cites="boud2016">(<a href="#ref-boud2016" role="doc-biblioref">Boud and Soler 2016</a>)</span>. I believe this should become the primary and overarching goal of higher education institutions, to produce self-sustaining learners who work and live in communities of inquiy for the good of the world.</p>
<p>An example of how this is realized in my courses is that learners are free to choose their domains of inquiry in alignment with the intended outcomes of the course. One of the outcomes in EDCI 335 is</p>
<blockquote class="blockquote">
<p>Identify and evaluate various digital, networked, and open technologies and understand how they impact the learners and the learning process</p>
</blockquote>
<p>Learners have meaningful options when it comes to meeting this objective. They can demonstrate their knowledge by creating a short learning experience using a Notion site where participants are led through a lesson in Gender and Mental Health, as below:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/ilr-notion.png" class="img-fluid figure-img" alt="Screenshot of a learner-created lesson on Gender and Mental Health using Notion as the platform."></p>
<figcaption>Screenshot of a learner-created lesson on Gender and Mental Health using Notion as the platform.</figcaption>
</figure>
</div>
<p>Or, in LDRS 463, they may use Obsidian to highlight their sense-making processes using tags and a concept map.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/obsidian-screenshot.png" class="img-fluid figure-img" alt="Screenshot of a learner-created concept map using Obsidian as the platform"></p>
<figcaption>Screenshot of a learner-created concept map using Obsidian as the platform.</figcaption>
</figure>
</div>
<p>By encouraging learners to customize their outputs and review each others’ work, they are allowed to engage in work that is more relevant to their own lives, and more likely to be able to sustain their learning after my course has completed.</p>
<p>The most effective process of me coming to know what the learner knows is to schedule 10-15 minute synchronous assessment conversations with learners where they present their work. I thus have the opportunity in the moment to probe their thinking about their work and to make a determination of the authenticity of their performance.</p>
<p>In summary, I believe that all learners have inherent rights and dignity, that teaching and learning is a relationship best described as a cognitive apprenticeship, and that meaningful work and conversations are the best ways to certify that learning has occured.</p>
</section>
</section>
<section id="teaching-interests" class="level2">
<h2 class="anchored" data-anchor-id="teaching-interests">Teaching Interests</h2>
<p>Teaching is a profound passion of mine, particularly when it allows me to apply my research findings in the classroom. My teaching experience includes junior and senior high school in both public and private high schools in BC and Alberta; internationally as an assistant language teacher in Japan; and in both undergraduate and graduate courses in higher education. I have taught a diverse range of subjects in grades 8-12, including physical education, digital media studies, outdoor education, sports medicine, science, English, and math.</p>
<p>At the University of Victoria, I co-designed and taught three online undergraduate courses: Learning Design, Distributed and Open Learning, and Social Media and Personalized Learning. These courses use WordPress as the primary hub of networked interactions, enabling students to personalize their web presence while acquiring critical digital literacy skills by engaging with the open web. (see my 2022 proceedings on multi-section course design <span class="citation" data-cites="irvineMultiSectionOpenCourse2022">(<a href="#ref-irvineMultiSectionOpenCourse2022" role="doc-biblioref">Irvine et al. 2022</a>)</span> as an example of how I share my practice in scholarly venues).</p>
<p>One of the highlights of my undergraduate teaching experience was co-designing and teaching in parallel with a fellow Ph.D.&nbsp;student during the early stages of the global COVID-19 pandemic. This collaborative process was mutually supportive and helped us navigate the complexities of teaching undergraduates in an innovative, technology-integrated context. <a href="https://otessa.org/2021/abstracts/experiencing-a-cognitive-apprenticeship-in-the-context-of-co-designing-and-co-teaching-an-undergraduate-course/" target="_blank">Our experience is documented in a presentation at the OTESSA21 conference at the Congress of the Social Sciences and Humanities</a>. I also co-designed and taught Coaching for Transformational Blended Learning, a course in the Graduate Certificate in Adult Learning: Coaching and Facilitation at TWU. This course takes an experiential approach to coaching individual learners and facilitating group processes in educational contexts. At the undergraduate level at TWU, I collaborated with an instructional designer to create an introductory online course called Learning with Technology which enrolled its first learners in the Fall of 2024. This course helps learners understand the affordances of technology for sense-making in learning environments by teaching them a technology-integrated workflow that maintains their personal privacy and teaches learners how to build networks of knowledge and learning using Obsidian, Zotero, and WordPress.</p>
</section>
<section id="teaching-effectiveness" class="level2">
<h2 class="anchored" data-anchor-id="teaching-effectiveness">Teaching Effectiveness</h2>
<p>The following is a table summarizing courses I have taught, including a synopsis of learner ratings of their experience with me as their instructor. Note that several courses did not meet the threshold for reporting ratings as there were too few submissions of learner experience surveys.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Course</th>
<th style="text-align: right;">Class Size</th>
<th style="text-align: right;">Responses</th>
<th style="text-align: right;">pct_good</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FA 2024</td>
<td style="text-align: left;">LDRS463/663</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">SP 2024</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">67</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FA 2023</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">SP 2023</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SP 2022</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">67</td>
</tr>
<tr class="even">
<td style="text-align: left;">SP 2022</td>
<td style="text-align: left;">EDCI338</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FA 2021</td>
<td style="text-align: left;">EDCI335</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">FA 2021</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SU 2021</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">SU 2021</td>
<td style="text-align: left;">EDCI335</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SP 2021</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">FA 2020</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SU 2020</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">SU 2020</td>
<td style="text-align: left;">EDCI339</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SU 2020</td>
<td style="text-align: left;">EDCI335</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">SU 2019</td>
<td style="text-align: left;">LDRS663</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SU 2019</td>
<td style="text-align: left;">EDCI339</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">SU 2019</td>
<td style="text-align: left;">EDCI335</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">75</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="efforts-to-improve-teaching" class="level2">
<h2 class="anchored" data-anchor-id="efforts-to-improve-teaching">Efforts to Improve Teaching</h2>
<p>Early in my higher education teaching career, there was a pattern of learners not being satisfied with my feedback practices. As I grew as an instructor in online environment, I began implementing more relational assessment and feedback practices as outlined in my teaching philosophy statement. One change that I have consistently implemented since those early efforts is being more intentional and explicit about the connections between the intended learning outcomes in the course and the assessment tasks required of learners. I have found that when learners are more aware of those connections, there is greater willingness to engage in the acivities that lead to success in learning. Further, when there are clear connections between intended outcomes and assessment activities, I can be explicit about any areas that may require further work and help learners bridge any gaps between their ability and the intended outcomes. The final area of growth in my teaching has been the implementation of assessment conversations which provide opportunity for a more relational approach to assessment. Learners have told me that this approach, while different from their previous experience, has allowed them to be more comfortable in exploring ideas tentatively rather than hoping that they produce the ‘correct’ answer. These approaches and strategies were informed by my dissertation work on the Technology-integrated Assessment Framework.</p>
</section>
<section id="pedagogical-innovations" class="level2">
<h2 class="anchored" data-anchor-id="pedagogical-innovations">Pedagogical Innovations</h2>
<p>In January 2022, I trialled an online course structure built on GitHub for learner contributions and WordPress for learner reflections, which allowed me to track more closely the work that learners were doing and who was contributing to cooperative projects. While there was a longer period of time required to ensure that all learners were comfortable using the platforms, it proved to be useful as an exploration of how openness can be realized in online learning environments. The end result of the course was a co-created website with leaerner contributions clearly visible and my interatctions in the asynchronous environment recorded. <a href="https://cmadland.github.io/edci338-202201">Please feel free to explore the site. Note that it is unchanged since the end of the course.</a></p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="publications-focused-on-assessment-and-evaluation" class="level1">
<h1>Publications Focused on Assessment and Evaluation</h1>
<p>Please see the following articles I published in the OTESSA Journal (May 2024):</p>
<p>Madland, C., Irvine, V., DeLuca, C., &amp; Bulut, O. (2024). <a href="https://doi.org/10.18357/otessaj.2024.4.1.57">Technology-Integrated Assessment: A Literature Review.</a> <em>The Open/Technology in Education, Society, and Scholarship Association Journal, 4</em>(1), 1–48. <a href="https://scholar.google.com/citations?view_op=view_citation&amp;hl=en&amp;user=AP34TNkAAAAJ&amp;citation_for_view=AP34TNkAAAAJ:zYLM7Y9cAGgC">Google Scholar Citations</a></p>
<p>Madland, C., Irvine, V., DeLuca, C., &amp; Bulut, O. (2024). <a href="https://doi.org/10.18357/otessaj.2024.4.1.63">Developing the Technology-Integrated Assessment Framework.</a> <em>The Open/Technology in Education, Society, and Scholarship Association Journal, 4</em>(1), 1–19. <a href="https://scholar.google.com/citations?view_op=view_citation&amp;hl=en&amp;user=AP34TNkAAAAJ&amp;citation_for_view=AP34TNkAAAAJ:Tyk-4Ss8FVUC">Google Scholar Citations</a></p>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-bloom1984" class="csl-entry" role="listitem">
Bloom, Benjamin. 1984. <span>“The 2 Sigma Problem: The Search for Methods of Group Instruction as Effective as One-to-One Tutoring.”</span> <em>Educational Researcher</em> 13: 4–16.
</div>
<div id="ref-boud2016" class="csl-entry" role="listitem">
Boud, David, and Rebeca Soler. 2016. <span>“Sustainable Assessment Revisited.”</span> <em>Assessment &amp; Evaluation in Higher Education</em> 41 (3): 400–413. <a href="https://doi.org/10.1080/02602938.2015.1018133">https://doi.org/10.1080/02602938.2015.1018133</a>.
</div>
<div id="ref-carless2019" class="csl-entry" role="listitem">
Carless, David. 2019. <span>“Feedback Loops and the Longer-Term: Towards Feedback Spirals.”</span> <em>Assessment &amp; Evaluation in Higher Education</em> 44 (5): 705–14. <a href="https://doi.org/10.1080/02602938.2018.1531108">https://doi.org/10.1080/02602938.2018.1531108</a>.
</div>
<div id="ref-hattie2007" class="csl-entry" role="listitem">
Hattie, John, and Helen Timperley. 2007. <span>“The Power of Feedback.”</span> <em>Review of Educational Research</em> 77 (March): 81–112. <a href="https://doi.org/10.3102/003465430298487">https://doi.org/10.3102/003465430298487</a>.
</div>
<div id="ref-irvineMultiSectionOpenCourse2022" class="csl-entry" role="listitem">
Irvine, Valerie, Michael Paskevicius, Colin Madland, Rich McCue, and Verena Roberts. 2022. <span>“Multi-<span>Section Open Course Design</span>: <span>Design</span> and <span>Implications</span> for <span>Faculty</span>, <span>Sessional Instructors</span>, and <span>Learners</span>.”</span> In <em>Proceedings of the <span>Open</span>/<span>Technology</span> in <span>Education</span>, <span>Society</span>, and <span>Scholarship Association Conference</span></em>, 1–3. Online. <a href="https://doi.org/10.18357/otessac.2022.2.1.419">https://doi.org/10.18357/otessac.2022.2.1.419</a>.
</div>
<div id="ref-madlandDevelopingTechnologyIntegratedAssessment2024" class="csl-entry" role="listitem">
Madland, Colin, Valerie Irvine, Chris DeLuca, and Okan Bulut. 2024. <span>“Developing the <span>Technology-Integrated Assessment Framework</span>.”</span> <em>The Open/Technology in Education, Society, and Scholarship Association Journal</em> 4 (1): 1–19. <a href="https://doi.org/10.18357/otessaj.2024.4.1.63">https://doi.org/10.18357/otessaj.2024.4.1.63</a>.
</div>
<div id="ref-madlandDigitalPlatformsAlgorithmic2022" class="csl-entry" role="listitem">
Madland, Colin, Maxwell Ofosuhene, and Jennifer Adkins. 2022. <span>“Digital <span>Platforms</span> and <span>Algorithmic Erasure</span>: <span>What</span> Are the <span>Implications</span>?”</span> In <em><span>OTESSA Conference</span> 2022</em>. Online: <span>Open/Technology in Education Society and Scholarship Association</span>. <a href="https://doi.org/10.18357/otessac.2022.2.1.137">https://doi.org/10.18357/otessac.2022.2.1.137</a>.
</div>
<div id="ref-madlandSelfDeterminationIndigenousOnline2021" class="csl-entry" role="listitem">
Madland, Colin, and Jean-Paul Restoule. 2021. <span>“Self-<span>Determination</span> in <span>Indigenous Online Education</span>.”</span> <em>The Open/Technology in Education, Society, and Scholarship Association Conference</em> 1 (1): 1–7. <a href="https://doi.org/10.18357/otessac.2021.1.1.147">https://doi.org/10.18357/otessac.2021.1.1.147</a>.
</div>
<div id="ref-ramsdenLearningTeachHigher2003" class="csl-entry" role="listitem">
Ramsden, Paul. 2003. <em>Learning to <span>Teach</span> in <span>Higher Education</span></em>. Routledge. <a href="https://doi.org/10.4324/9780203507711">https://doi.org/10.4324/9780203507711</a>.
</div>
<div id="ref-tai2018" class="csl-entry" role="listitem">
Tai, Joanna, Rola Ajjawi, David Boud, Phillip Dawson, and Ernesto Panadero. 2018. <span>“Developing Evaluative Judgement: Enabling Students to Make Decisions about the Quality of Work.”</span> <em>Higher Education</em> 76 (3): 467–81. <a href="https://doi.org/10.1007/s10734-017-0220-3">https://doi.org/10.1007/s10734-017-0220-3</a>.
</div>
<div id="ref-tessaro2018" class="csl-entry" role="listitem">
Tessaro, Danielle, Jean-Paul Restoule, Patricia Gaviria, Joseph Flessa, Carlana Lindeman, and Coleen Scully-Stewart. 2018. <span>“The Five r’s for Indigenizing Online Learning: A Case Study of the First Nations Schools’ Principals Course.”</span> <em>Canadian Journal of Native Education</em> 40 (1): 125–43. <a href="https://www.researchgate.net/publication/328289320_The_Five_R%27s_for_Indigenizing_Online_Learning_A_Case_Study_of_the_First_Nations_Schools%27_Principals_Course">https://www.researchgate.net/publication/328289320_The_Five_R%27s_for_Indigenizing_Online_Learning_A_Case_Study_of_the_First_Nations_Schools%27_Principals_Course</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>